### ISSUE TITLE
Server Side Requirements

### ISSUE THREAD

**Issue by rooftoprafa** [qutheory/vapor#106]
Hello, 
this may look as a dumb question, but has a PHP developer I never faced any problems with shared hosting because every hosting has PHP. 

I understand that to use Swift and Vapor on the web it may require some special configurations or instalations. 
So, what are those requirements? Is there a guide or something to test in heroku.com?

**Comment by tannernelson** [comment]
Check out the setup page on the Wiki https://github.com/qutheory/vapor/wiki/Setup

**Comment by rooftoprafa** [comment]
Thats what I was looking for. Thanks :D
