### ISSUE TITLE
Hello world not working

### ISSUE THREAD

**Issue by svanimpe** [qutheory/vapor#109]
The following app
```
import Vapor
let app = Application()
app.get("welcome") { request in
  return "Hello from Vapor"
}
app.start()
```
returns a 404 when requesting `localhost/welcome`.

Server output:
```
[2016-03-06 19:25:10 +0000] [INFO] Server has started on port 80
[2016-03-06 19:25:12 +0000] [VERBOSE] Received Get request for /welcome
[2016-03-06 19:25:12 +0000] [WARNING] Response had no 'Content-Type' header.
```

I'm running on Ubuntu 15.10 using the March 1 snapshot of Swift and Vapor 0.2.8.

**Comment by svanimpe** [comment]
Using the `Response` class does work:
```
app.get("welcome") { request in
  let response = Response(status: .OK, text: "Hello from Vapor")
  return response
}
```

**Comment by svanimpe** [comment]
A possible fix is to change `extension String: ResponseConvertible` to `extension Swift.String: ResponseConvertible` in `ResponseConvertible.swift`. Maybe type String is referring to NSString from Foundation?

**Comment by tannernelson** [comment]
Is this happening on OS X or Ubuntu?

If you can confirm `Swift.String` fixes it, could you create that as a PR?

**Comment by svanimpe** [comment]
As the original comment said: "I'm running on Ubuntu 15.10 using the March 1 snapshot of Swift and Vapor 0.2.8."
The change fixed it for me. I'll create it a pull request so others can try it out as well.

**Comment by tannernelson** [comment]
Oh sorry, missed the last line. A PR would be great.

**Comment by LoganWright** [comment]
Linking: #117
