### ISSUE TITLE
Json cannot be initialized using Int

### ISSUE THREAD

**Issue by svanimpe** [qutheory/vapor#111]
The following code (where `id` is of type `Int`)
```
var data: [String: Json] = [:]
data["id"] = Json(id)
```
does not compile with the error `call can throw, but it is not marked with 'try' and the error is not handled` (referring to the `Json` initializer).

Should this be possible? I can wrap `id` in a `Double` as a workaround, but the error was pretty confusing so I wonder if this is a bug.

This is using Vapor 0.2.8 on Ubuntu 15.10 with Swift snapshot of March 1.

**Comment by LoganWright** [comment]
I think this is because there is a Json convertible property that is meant to infer some things in a fail able way. 

For ints and other primitives, it's better to create Json directly, i.e.: 

Js["key"] = .IntValue(1)

**Comment by ketzusaka** [comment]
The error is misleading. There's not an initializer for Json that accepts an Int, but there is one for Double. Maybe we should add one, but I don't believe its a bug. Wrapping in a Double is safe for now, or you can extend Json to take an Int.

**Comment by svanimpe** [comment]
@LoganWright There is no `.IntValue` member in the `Json` enum?

**Comment by LoganWright** [comment]
Is it IntegerValue? Sorry, I'm on mobile at the moment. 

I agree, a pure int initializer would be valuable, it shouldn't be too tricky to add

**Comment by LoganWright** [comment]
Actually, I see what ketzusaka was saying now. You'll have to use double or add 'try' in the interim

**Comment by svanimpe** [comment]
This isn't working for me. Trying `Json(1)` results in the following error:

``
error: ambiguous use of 'init'
      json["id"] = Json(1)
                   ^
Vapor.Json:13:12: note: found this candidate
    public init<T : SignedIntegerType>(_ value: T)
           ^
Vapor.Json:11:12: note: found this candidate
    public init<T : JsonConvertible>(_ any: T) throws
```

This is on Ubuntu.

**Comment by LoganWright** [comment]
It seems like we might not be able to use in parallel, at least not without some sort of specified argument.

I think the best option here is to remove the `throw` from the specific integer methods, so:

```
    public func jsonRepresentation() -> Json {
        let double = Double(IntMax(self.toIntMax()))
        return .from(double)
    }
```

In the convertible declaration, then you could call `1.jsonRepresentation()` or maybe we could shorten it to just be `1.toJson()`.

Until I can add this, it might be a good idea to just go for `.DoubleValue(1)`
