### ISSUE TITLE
Dangerous `rm -rf` in CLI

### ISSUE THREAD

**Issue by zef** [qutheory/vapor#157]
Was just browsing around and noticed [this](https://github.com/qutheory/vapor/blob/master/vapor#L167):

```
            let _ = try? run("rm -rf \(name)/.git")
```

Thought I should say something since (it looks like) running `vapor new / ` would run `rm -rf / /.git`, or other similar bad things.

Thanks!

**Comment by tannernelson** [comment]
that seems like it would function normally unless I'm mistaken

**Comment by zef** [comment]
Doing something like that would remove the user's root directory right? It's just that you can't expect people to know that an unchecked `rm` is going to be performed inside your command. It's not like people should be typing something like that on purpose, but if it was an accident or it somehow happened, it would be really terrible.

So basically I think it's the responsibility of a tool like this to make sure that kind of thing is not even possible. In this specific case maybe you could check that the directory exists and that it's a .git directory before running the command. Make sure there are no spaces in the name that's passed in, something like that.

Hope that helps!

**Comment by tannernelson** [comment]
If you do `vapor new /` it will create a new vapor project in the root directory of your application then remove the `.git` folder normally. 

It can only delete something with `.git` after it. Also it's not run as sudo.

**Comment by zef** [comment]
Thanks for the response... Last thing: the way it would delete something undesirable is if there was whitespace: `vapor new / something` would call `rm -rf / something`, and `rm` would execute for both `/` and `something.git/`. `/` is really just a placeholder for whatever undesirable thing you don't actually want deleted. Looking at the rest it might not get that far if the `git clone` failed due to weird arguments or something. Regardless just seems scary to me to pass that straight through without doing any checking.

**Comment by tannernelson** [comment]
Ah okay, I see what you mean. Yeah that would fail the `git clone` for sure.

**Comment by tannernelson** [comment]
People once thought it was scary to drive with tanks of explosive liquid attached to the bottom of their cars.

**Comment by tannernelson** [comment]
Thanks @shnhrrsn. I'll merge this.
