### ISSUE TITLE
Build Errors when building with Vapor 0.3.5

### ISSUE THREAD

**Issue by Prince2k3** [qutheory/vapor#158]
![screen shot 2016-03-27 at 1 39 32 pm](https://cloud.githubusercontent.com/assets/2805285/14067089/c936f7e2-f421-11e5-878d-3b6c884bcacc.png)

When building an app that has Vapor as a package. I am getting a build error about JayExample not finding a module. I think JayExample needs to be excluded within its projects. 

Not sure If should post this here or on the Jay git. But error began when I added Vapor as a package.

**Comment by tannernelson** [comment]
Jay is being removed next update.
