### ISSUE TITLE
main.swift:2:8: error: no such module 'VaporZewoMustache'

### ISSUE THREAD

**Issue by SpectralDragon** [qutheory/vapor#169]
````
main.swift:2:8: error: no such module 'VaporZewoMustache'
import VaporZewoMustache
````
Why? This new project and i can't build him :(

**Comment by tannernelson** [comment]
Can you paste your `Package.swift`?

**Comment by SpectralDragon** [comment]
> Can you paste your Package.swift?
I just deleted all line codes with VaporZewo :D And, this work! 
I download demo example and try build him, but i get this error :)

**Comment by tannernelson** [comment]
Okay, sounds good. There must have been some issue with the swift package manager not downloading our VaporZewoMustache package. Glad it's working now, though. I'll close this.

**Comment by baims** [comment]
i'm having this same error now. Here's my Package.swift
`import PackageDescription

let package = Package(
    name: "VaporApp",
    dependencies: [
        .Package(url: "https://github.com/qutheory/vapor.git", majorVersion: 0,$
        .Package(url: "https://github.com/qutheory/vapor-zewo-mustache.git", ma$
    ],
    exclude: [
        "Deploy",
        "Public",
        "Resources",
                "Tests",
                "Database"
    ]
)`
