### ISSUE TITLE
Error compiler depedency

### ISSUE THREAD

**Issue by d3roch4** [qutheory/vapor#170]
error: The dependency graph could not be satisfied because an update to `https://github.com/SwiftX/C7.git' is required

**Comment by tannernelson** [comment]
Some of the dependencies we have broke earlier. There will be a merge soon that fixes it.

**Comment by tannernelson** [comment]
Vapor 0.5.0 is out now and solves this issue. Upgrade to `minor: 5` in your `Package.swift`
