### ISSUE TITLE
How to intercept 404 and customize return data? 🍦🍦🍦

### ISSUE THREAD

**Issue by Jinxiansen** [qutheory/vapor#1716]
When I use **Vapor 3**, I want to intercept and customize the **Abort(.notFound)** state in the inheritance of **Middleware**'s **ExceptionMiddleware** class, but I don't know how to do interception here.

> English is not my native language; please excuse typing errors.

**Comment by qq565999484** [comment]
You can look at the **errormiddleeware** sourcecode
