### ISSUE TITLE
main.swift:2:8: error: no such module 'VaporZewoMustache'

### ISSUE THREAD

**Issue by baims** [qutheory/vapor#173]
I'm having this error

```
App/main.swift:2:8: error: no such module 'VaporZewoMustache'
import VaporZewoMustache
```

And here's my Package.swift
```
import PackageDescription

let package = Package(
    name: "VaporApp",
    dependencies: [
        .Package(url: "https://github.com/qutheory/vapor.git", majorVersion: 0, minor: 5),
        .Package(url: "https://github.com/qutheory/vapor-zewo-mustache.git", majorVersion: 0, minor: 2)
    ],
    exclude: [
        "Deploy",
        "Public",
        "Resources",
                "Tests",
                "Database"
    ]
)
```

**Comment by tannernelson** [comment]
That's so strange. Can you paste me which Swift snapshot your using and the entire output of the build process?

**Comment by baims** [comment]
```
Building...
App/main.swift:2:8: error: no such module 'VaporZewoMustache'
import VaporZewoMustache
       ^

Usage: vapor build [file1, file2, ...]
Make sure you are running Apple Swift version 2.2.
Run swiftc --version to check your version.
```

and here's swift --version
```
Swift version 2.2 (swift-2.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by tannernelson** [comment]
Ah, there's the trouble. Swift 2.2 doesn't support Swift Package Manager, so unfortunately it does not care at all what is in your `Package.swift` file. You can only use core Vapor with Swift 2.2.

If you upgrade to the latest development snapshot (March 24) you will be able to use the latest Vapor (0.5) and all of its related packages. There are instructions on how to do this in the Getting Started section of the Vapor wiki.

**Comment by baims** [comment]
Thanks it's working now with Swift 3 !

**Comment by tannernelson** [comment]
Let us know if you make anything cool. And feel free to reach out to us on [Slack](http://slack.qutheory.io) if you have any questions.
