### ISSUE TITLE
swift 3.0 package error

### ISSUE THREAD

**Issue by litan1106** [qutheory/vapor#178]
Ubuntu 14.04
Swift 3.0

ubuntu-trusty-64$ swift build
Cloning https://github.com/qutheory/vapor.git
git clone --recursive --depth 10 https://github.com/qutheory/vapor.git /home/vagrant/Swifts/vapor-3.0/Packages/vapor

Segmentation fault (core dumped)

**Comment by tannernelson** [comment]
Which Swift 3.0 snapshot are you using?

**Comment by litan1106** [comment]
swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a

**Comment by tannernelson** [comment]
That's the proper installation. What type of machine? If it hasn't started trying to build the project yet when it's crashing, it must be an issue with Swift on your system.

**Comment by corybohon** [comment]
I was having this same issue occur, and found it to be that git was not installed on the system prior to running the `vapor build` command.
