### ISSUE TITLE
"Default" route

### ISSUE THREAD

**Issue by randomiser** [qutheory/vapor#1799]
Hi there,

Thanks for building Vapor its shaping up to be a great product.

Is it possible - using the current codebase - to have a catch all "default" route that will be returned in the case that no other route matches? 

Can't seem to see anything like this at present.

Cheers,
Matt

**Comment by 0xTim** [comment]
@randomiser you can do

```swift
router.get(PathComponent.anything) { req in
    return "Any path"
}
```

**Comment by randomiser** [comment]
Hi thanks for that! Hadn't spotted that.

Note: It mostly works. Although if you add extra characters to a route .i.e.

```
router.get("hello/world", use: HelloWorldController())

router.get(PathComponent.anything) { req in
    return "My custom output"
}

http://localhost:8080/hello/worldabc"
``` 

It isn't caught by the above. Is that the expected behaviour?

**Comment by JovanMilenkovic** [comment]
Try replacing PathComponent.anything with PathComponent.catchall. Your issue can be described as expected behavior since .anything matches anything that IS NOT in other routes

**Comment by randomiser** [comment]
Thanks good to know. There so much extra stuff the in the Vapor API that isn't documented for end users. Would be good to include an explanation around this for example as it will be a very common question.

**Comment by JovanMilenkovic** [comment]
I'm under the impression that most of the basic stuff are well documented in the docs, and the code in vapor itself is always documented. Also, I'm feeling like you should not be doing this anyway, this has to be solvable in other way instead of a "default" route.
