### ISSUE TITLE
CircleCI in progress

### ISSUE THREAD

**Issue by mpclarkson** [qutheory/vapor#183]
@tannernelson I have the tests running in Circle in 05 minutes 19 seconds on Ubuntu 14.04. How does this compare to Travis?

One issue with Circle is that a build environment must be either `OSX` or `Linux` - it doesn't seem possible to run tests on both. I will investigate this further... If it is not possible, I assume it will be a showstopper?

**Comment by mpclarkson** [comment]
Looks like it is not possible: https://discuss.circleci.com/t/how-to-use-circleci-for-linux-xcode-in-one-project/693

**Comment by LoganWright** [comment]
@mpclarkson good find, I'm really surprised by that. It definitely seems like a deal breaker to me. I think testing on both platforms is more important than saving on build times. We should revisit when/if the feature gets added. In the meantime, let's all upvote the feature request to see if we can give it some priority:

https://discuss.circleci.com/t/support-for-multiple-oss/1779

**Comment by mpclarkson** [comment]
Agreed.

**Comment by ketzusaka** [comment]
I don't think that  Travis is very slow. It's the generated routes that slows builds down pretty drastically.

**Comment by tannernelson** [comment]
@ketzusaka It's not the build time we're trying to reduce, it's the time waiting in the queue. But it looks like this will be impossible anyway. Thanks for looking into it @mpclarkson. Gonna close this for now.
