### ISSUE TITLE
Build fails for swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a 

### ISSUE THREAD

**Issue by LanceWithWang** [qutheory/vapor#185]
The problem does not occur when using swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.
`LanceiMacWiFi:HelloSwift meixiandongpinshangcheng$ swift build
2016-04-19 13:24:30.933 xcodebuild[8803:1394745] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-19 13:24:31.423 xcodebuild[8804:1394920] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Cloning https://github.com/qutheory/vapor.git
Resolved version: 0.5.3
Cloning https://github.com/swiftx/s4.git
Resolved version: 0.2.1
Cloning https://github.com/SwiftX/C7.git
Resolved version: 0.2.0
Cloning https://github.com/Zewo/String.git
Resolved version: 0.4.3
Cloning https://github.com/Zewo/OS.git
Resolved version: 0.4.2
Cloning https://github.com/Zewo/JSON.git
Resolved version: 0.4.2
Cloning https://github.com/Zewo/InterchangeData.git
Resolved version: 0.4.3
Cloning https://github.com/Zewo/Data.git
Resolved version: 0.4.9
Cloning https://github.com/qutheory/Hummingbird.git
Resolved version: 2.0.0
Cloning https://github.com/ketzusaka/Strand
Resolved version: 1.1.0
Cloning https://github.com/CryptoKitten/HMAC.git
Resolved version: 0.3.1
Cloning https://github.com/CryptoKitten/CryptoEssentials.git
Resolved version: 0.2.1
Cloning https://github.com/CryptoKitten/SHA2.git
Resolved version: 0.1.0
Cloning https://github.com/qutheory/vapor-stencil.git
Resolved version: 0.2.0
Cloning https://github.com/qutheory/stencil.git
Resolved version: 0.5.4
Cloning https://github.com/qutheory/path-kit.git
Resolved version: 0.6.3
2016-04-19 13:28:16.940 xcodebuild[10064:1414896] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Compiling Swift Module 'C7' (14 sources)
Compiling Swift Module 'OperatingSystem' (1 sources)
Compiling Swift Module 'Strand' (1 sources)
Compiling Swift Module 'PathKit' (1 sources)
Compiling Swift Module 'String' (1 sources)
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/Strand-1.1.0/Sources/Strand.swift:29:38: error: nil cannot initialize specified type 'pthread_t' (aka 'UnsafeMutablePointer<_opaque_pthread_t>')
    private var pthread: pthread_t = nil
                                     ^
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/Strand-1.1.0/Sources/Strand.swift:40:30: error: cannot pass immutable value as inout argument: implicit conversion from 'pthread_t' to 'pthread_t?' requires a temporary
        guard pthread_create(&pthread, nil, runner, pointer) == 0 else { throw StrandError.threadCreationFailed }
                             ^~~~~~~~
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/Strand-1.1.0/Sources/Strand.swift:73:12: error: nil is incompatible with return type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePointer<()>')
    return nil
           ^
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:28:31: warning: extraneous duplicate parameter name; 'size' already has an argument label
    public static func buffer(size size: Int) -> [Int8] {
                              ^~~~~
                              
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:238:21: warning: extraneous duplicate parameter name; 'compress' already has an argument label
    func fixSlashes(compress compress: Bool = true, stripTrailing: Bool = true) -> String {
                    ^~~~~~~~~
                    
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:59:16: error: argument labels '(_:)' do not match any available overloads
        return trim(CharacterSet.whitespaceAndNewline)
               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:59:16: note: overloads for 'trim' exist with these partially matching parameter lists: (characters: CharacterSet), (left: CharacterSet), (right: CharacterSet)
        return trim(CharacterSet.whitespaceAndNewline)
               ^
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:71:39: error: missing argument label 'character:' in call
            if !characterSet.contains(character) {
                                      ^
                                      character: 
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/String-0.4.3/Source/String.swift:84:39: error: missing argument label 'character:' in call
            if !characterSet.contains(character) {
                                      ^
                                      character: 
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/C7-0.2.0/Sources/AsyncStream.swift:4:18: warning: extraneous duplicate parameter name; 'length' already has an argument label
    func receive(length length: Int, result: (Void throws -> Data) -> Void)
                 ^~~~~~~
                 
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/C7-0.2.0/Sources/AsyncStream.swift:5:15: warning: extraneous duplicate parameter name; 'data' already has an argument label
    func send(data data: Data, result: (Void throws -> Void) -> Void)
              ^~~~~
              
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/C7-0.2.0/Sources/Data.swift:34:26: error: method 'replaceSubrange(subRange:with:)' has different argument names from those required by protocol 'RangeReplaceableCollection' ('replaceSubrange(_:with:)')
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Byte>(subRange: Range<Int>, with newElements: C) {
                         ^
                                                                                          _ 
Swift.RangeReplaceableCollection:16:26: note: requirement 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Iterator.Element>(_ subRange: Range<Self.Index>, with newElements: C)
                         ^
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/C7-0.2.0/Sources/Data.swift:34:26: error: method 'replaceSubrange(subRange:with:)' has different argument names from those required by protocol 'RangeReplaceableCollection' ('replaceSubrange(_:with:)')
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Byte>(subRange: Range<Int>, with newElements: C) {
                         ^
                                                                                          _ 
Swift.RangeReplaceableCollection:16:26: note: requirement 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Iterator.Element>(_ subRange: Range<Self.Index>, with newElements: C)
                         ^
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/PathKit-0.6.3/Sources/PathKit.swift:804:59: error: value of optional type 'UnsafeMutablePointer<Int8>?' not unwrapped; did you mean to use '!' or '?'?
          if let path = String(validatingUTF8: gt.gl_pathv[index]) {
                                                          ^
                                                                 !
/Users/meixiandongpinshangcheng/Music/HelloSwift/Packages/PathKit-0.6.3/Sources/PathKit.swift:818:22: error: missing argument label 'pattern:' in call
    return Path.glob((self + pattern).description)
                     ^
                     pattern: 
<unknown>:0: error: build had 4 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/bin/swift-build-tool -f /Users/meixiandongpinshangcheng/Music/HelloSwift/.build/debug.yaml default`
which I have no idea how to solve right now. Do you know what might be a possible cause?

**Comment by LoganWright** [comment]
@LanceWithWang The latest snapshot support for version `0.5.x` is the 03-24 version. You'll have to downgrade or wait for us to get 04-12 support. My guess is in the next day or two. I'll try and get it in tonight as a lot of our dependencies are also  upgrading today.

**Comment by LanceWithWang** [comment]
Thanks you,I used 03-24，it succeeded， I will take its to deploy server

**Comment by LoganWright** [comment]
Currently being addressed in #186 

Everything is building, but I need to resolve an issue w/ Travis.

**Comment by LoganWright** [comment]
@LanceWithWang 04-12 snapshot is ready w/ tag 0.6.0 👍
