### ISSUE TITLE
Vapor.Json is not initializable with [Vapor.Json]

### ISSUE THREAD

**Issue by Joannis** [qutheory/vapor#188]
Vapor's Json enum can only be initialized with raw variables, Zewo.JSON or [Zewo.JSON].

**Comment by tannernelson** [comment]
Can you give a code snippet example of this?

**Comment by Joannis** [comment]
See #194

**Comment by Joannis** [comment]
I opened this ticket twice. I didn't remember adding it before. Sorry!
