### ISSUE TITLE
"Response had no 'Content-Type' header" warning when sending CSS

### ISSUE THREAD

**Issue by czechboy0** [qutheory/vapor#192]
When I have a simple Vapor server with an index file and CSS in `Public/stylesheets`, every time the page is loaded the server logs a warning because no `Content-Type` was attached.

```
[1461329360] [INFO] GET /
[1461329360] [INFO] GET /stylesheets/style.css
[1461329360] [WARNING] Response had no 'Content-Type' header.
```

We can do either
- detect a couple of basic files usually present in Public and attach the correct content type (recommended)
- ignore the warning and disable it

Thoughts?

**Comment by tannernelson** [comment]
Two solutions I see:
- Use Zewo's Media Type repo to determine the correct Content Type for `.css`
- Serve files using Nginx
