### ISSUE TITLE
Session token not generating when one already exists

### ISSUE THREAD

**Issue by Joannis** [qutheory/vapor#193]
When I already have an identifier in the "vapor-session" cookie it takes the existing identifier instead of generating a new one. Thus obstructing any functionality I wanted to have when generating a new identifier like for example saving it to the database.

Also; I think it's unsafe to take an existing identifier instead of generating a new (random) one as (the default) session driver doesn't check the IP. So anyone could enter a cookie they made up on my PC and use it on their own PC to steal my session.

**Comment by tannernelson** [comment]
I don't quite understand the issue here. In order to hijack your session, the attacker would need to know your session cookie. 

Additionally, if the session cookie is regenerated every time, how would you persist a session?

**Comment by Joannis** [comment]
You don't regenerate it every time. You generate a new one if the SessionDriver doesn't know the session token. Currently you expect anyone with a "vapor-session" cookie to be familiar with the SessionDriver. But if it's not you force the SessionDriver to accept this new token.

If I walk up to any PC now and create a cookie "vapor-session=abc" it'll accept "abc" as the amazing token for this user. Now I can (from any PC) enter "abc" as my "vapor-session" using the same method and I'll be logged into their account. So you need to force your SessionDrivers to check their IP address I think. Or simply regenerate the token if the SessionDriver isn't familiar with the Token yet.

Besides that the next issue arises. I'm making a MongoSessionDriver which relies on new users getting their identifier stored in the database. Now this isn't a problem with MongoDB as I can "upsert" information. (Update if exists, otherwise insert). But with SQL you'll need to INSERT and then UPDATE. So an SQLSessionDriver will have problems with "makeSessionIdentifier" in the case the cookie is already set I.E. after removing old sessions from the database.

**Comment by ketzusaka** [comment]
I don't think you'd want to regenerate a session token eveytime. That would probably open the door to difficult bugs when a site has multiple Ajax requests or an API has many concurrent requests at the same time.

**Comment by tannernelson** [comment]
I see what Joannis is saying. Only generate a new token if they token they posted is not recognized.

**Comment by ketzusaka** [comment]
Ah my bad
