### ISSUE TITLE
`Hash` isn't publically initializable

### ISSUE THREAD

**Issue by Joannis** [qutheory/vapor#195]
My own SessionDriver can't be initialized since I can't get a `Hash` object as it's not publically initializable.

**Comment by tannernelson** [comment]
You should be able to access a `Hash` object off of `app.hash` if you init your `SessionDriver` after the Application has initialized. 

But we should find a more elegant solution to this for sure.

**Comment by LoganWright** [comment]
Hash can be passed into initialization through `init(hash:`, or accessed publicly after initialization. @Joannis reopen this if it doesn't address your issue 👍

**Comment by LoganWright** [comment]
Reopening. While I made hash publicly addable onto Application, it's not publicly initializable. See #336
