### ISSUE TITLE
WebSocket middelwares can't work

### ISSUE THREAD

**Issue by Joannis** [qutheory/vapor#198]
Currently in Vapor there is no way for Vapor to see if a stream has been upgraded to WebSocket. The result is that all WebSocket data passed to the WebSocket Middleware will be seen as normal HTTP traffic and will throw when receiving WebSocket data. I think a stream should be able to be marked as `websocket = true` so that Vapor knows not to interpret the Stream's information.

**Comment by tannernelson** [comment]
Can you provide some sample code of the issue and what you'd want it to look like?

**Comment by Joannis** [comment]
I can't explain why but I've got my WebSockets working now... I could tell you the problem I was facing but I think it doesn't matter now.
