### ISSUE TITLE
vapor.sh cert expired

### ISSUE THREAD

**Issue by TellowKrinkle** [qutheory/vapor#2038]
### Steps to reproduce

Attempt to visit https://apt.vapor.sh or run `eval "$(curl -sL https://apt.vapor.sh)"`

### Expected behavior

The site loads and the script sets up swift repos

### Actual behavior

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/3315070/63734939-d1384280-c843-11e9-9e71-e069d0fced81.png">
(The certificate expired on 2019/08/21)

### Environment

* Vapor Framework version: None
* Vapor Toolbox version: None
* OS version: macOS 10.14.5（18F132）

**Comment by MrLotU** [comment]
@joscdk

**Comment by joscdk** [comment]
@tellowkrinkle can you try again?
