### ISSUE TITLE
Fix project-wide spacing rules

### ISSUE THREAD

**Issue by czechboy0** [qutheory/vapor#204]
It seems like we have a mix of spaces and tabs in our source files. More: https://github.com/qutheory/vapor/pull/202#discussion_r61696563

**Comment by tannernelson** [comment]
Let's move to 4 spaces.

**Comment by tannernelson** [comment]
I checked all of the Vapor source and test files and they were spaces. The one exception is the generated file which should remain tabs to reduce file size and make it easier to produce.
