### ISSUE TITLE
Example not building on Linux

### ISSUE THREAD

**Issue by Jerrot** [qutheory/vapor#225]
I'm following the documentation on https://vapor.readme.io/docs/hello-world to create a first sample application, using the DEVELOPMENT-SNAPSHOT-2016-05-03-a as described.
I'm using Ubuntu 16.04 (forced installation of Swift for Ubuntu 15.10) and Swiftenv. 

Unfortunately, `vapor build` just ends up with a lot of build errors in Strand (1.1.0) and in Mustache (0.4.0), see 
[error_log.txt](https://github.com/qutheory/vapor/files/255412/error_log.txt) attached.

The build finally fails with 
`error: exit(1): /home/jerrot/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-05-03-a/usr/bin/swift-build-tool -f /home/jerrot/swift-server/vapor/hello-world/.build/debug.yaml`

If you require any more information, please don't hesitate to ask, thanks for all your efforts.

**Comment by tannernelson** [comment]
From the output you attached, it looks like you are trying to build a really old version of the packages.

Try running `vapor clean` (should remove the `Packages` and `.build` folders) and then building again.

**Comment by tannernelson** [comment]
Actually, it looks like the `vapor-example` repo had not been updated to support the 05-03 snapshot. It has now. Run `vapor new` again to get the latest, as the old one does not work with the 05-03 snapshot. (Downgrading your snapshot version is also an option).

**Comment by Jerrot** [comment]
I tried downgrading Swift step by step until the first March snapshot, but that didn't help. However, your fix to the dependencies of the example app perfectly solved everything now, thanks!
