### ISSUE TITLE
Unable to properly infer complex Json

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#23]
If I have the following command:

```
Route.get("complex") { request in
    let json = [
        "root" : [
            ["hello" : "world"],
            ["hello" : "mars"]
        ]
    ]
    return try Response(status: .OK, json: json)
}
```

It will work locally, but on Heroku, it will hit Mirror in the JsonSerializer and return `""`

If, I add `let json: [String : Any] = ...` then it will return `{ "root" : "" }` because it fails in parsing the nesting.

This can be reproduced locally, but requires a bit trickier response:

```Swift
Route.get("thing") { _ in
    let thing: [String : [String : Any]] = [
        "one" : [
            "hi" : "there"
        ],
        "two" : [
            "hi" : "again",
            "bye" : "sup"
        ]
    ]
    
    return thing
}
```

Then my only response is: `

**Comment by LoganWright** [comment]
FWIW, `NSJSONSerialization` ran on heroku for me, I also use a library https://github.com/gfx/Swift-PureJsonSerializer which might be nice to use if you'd prefer to stay truly pure Swift

**Comment by tannernelson** [comment]
Yeah the current JSON serializer for Linux is a placeholder for something better. I was hoping to hold out for Apple supporting pure `Dictionary` and `Array` objects in their Foundation serializer.

I will look into that repo you linked.

**Comment by tannernelson** [comment]
I took a look into a couple JSON serializers for supposedly "Swift on Linux" last night, and none of them worked. The current Linux compiler does not view `[String: Any]` as an `AnyObject` which they all seem to rely on. Or some rely on defining your JSON like this:

```swift
let response: JSON = [
     ....
]
```

I'm not a fan of this solution because this destroys the concise syntax of something like:

```swift
Route.get("...") { _ in
  return [
      ...
  ]
}
```

You can use the Foundation JSON serializer if you explicitly make all of your responses `NSDictionary`s with `NSString` keys, but that is a pain semantically. 

I can't see any solution now besides waiting for the compiler to get its weirdnesses figured out.

**Comment by LoganWright** [comment]
The pure Json one works for sure, I'll make a pull request in a bit

**Comment by LoganWright** [comment]
I see the problem with the requiring an explicit addition.

I've solved a similar problem w/ Json convertible types on top of pure json serializer.  I'll see if I can apply some of that here so the user could see just a standard concise syntax and we'd be able to convert it in the background.

**Comment by tannernelson** [comment]
If you could make a PR or link me to some examples of this working that would be helpful. Also, nice article on Medium. :+1:

**Comment by LoganWright** [comment]
@tannernelson Will do, might not be until tomorrow, but I have some code that should work for this.  I just need to break the convertible component out so we're not doing copy pasta between the two libs.

Glad you saw the medium post, I couldn't find your twitter to link you, let me know if you have one and I'll add it!

**Comment by tannernelson** [comment]
My twitter is @tanner0101

And that sounds good. Feel free to submit the PR early/incomplete if you want assistance working on it.

**Comment by LoganWright** [comment]
@tannernelson If you didn't see, we're up on http://iosdevweekly.com/ 

Hopefully can get some more traffic this way!  I've started some of the Json convertible stuff, I'll have a pr up soon hopefully :+1:

**Comment by tannernelson** [comment]
Awesome! :) Congrats. 

Also, check out issue #28. There is a potential solution for serializing and parsing mentioned there.

**Comment by mpclarkson** [comment]
Awesome coverage!

Matthew Clarkson

**Comment by tannernelson** [comment]
Added to roadmap.
