### ISSUE TITLE
pull request approval process

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor#242]
We should have a more structured Pull Request approval process that promotes good code, community visibility, and efficiency. 

At my current job, we use the emoji reaction system. When the original comment on a PR gets 3 or more thumbs up emojis, it is safe for the Assignee of the PR to merge it.

While this works well for a small team, I think since Qutheory already has over a hundred members and dozens of contributors, we could benefit from having Moderators.

Let's use this issue to discuss pros and cons and other possible choices.

**Comment by Prince2k3** [comment]
I like the Moderators approach with the emoji reaction system. With Moderators you have a more trusted circle of code and conduct maintainers.

**Comment by timominous** [comment]
I also agree with Moderators. In combination with the reaction system, the moderator/s can assume which PRs are agreed upon/needed. Also, the presence of moderators kind of ensures a code review process.

**Comment by Evertt** [comment]
👍  for the moderators combined with the reaction system.

**Comment by LoganWright** [comment]
I like squirrels :shipit:

**Comment by Evertt** [comment]
I don't understand xD
Is this meant as a *kick* for the thread?

**Comment by LoganWright** [comment]
lol, no @Evertt

No, but I could see why you thought that.

That emoji is the :shipit: try typing `:shipit:` it originated w/ <a href="https://www.quora.com/GitHub-What-is-the-significance-of-the-Ship-It-squirrel">GitHub </a>

I like a comment of a squirrel, some emojis, or other rodent like critter as an acceptance.

I don't get notified for upvotes, and the squirrels/emoji thing can be kind of fun.

**Comment by tannernelson** [comment]
Looks like the agreement is unanimous. Moderators will vote on new feature requests (issues) to pass them, and at least one thumbs up from a moderator is required to merge a PR.

The moderators group will start with Logan and I and we will add people who have contributed some code and want to be a part of it.
