### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by jchannon** [qutheory/vapor#243]
I just wanted to say as a contributor to a C# web framework, [Nancy](http://nancyfx.org), I love the look of Vapor!

Great docs, great examples and your API implementation is very similar to Nancy.

I want to start looking at Swift more so I'm hoping to use this framework when I get chance.

Great work, thanks!

🎉

**Comment by tannernelson** [comment]
Thanks a lot @jchannon :) Nancy looks very powerful–especially the ability to use regular expressions in the routing.

**Comment by jchannon** [comment]
Yup I tend not to use it for my apps, cause ya know Regex but we have route constraints which are helpful
```
Get["/user/{id:int}"] = parameters => 
{
    int id = parameters.id;
    return db.GetUserById(id);
}
```

**Comment by jchannon** [comment]
For validation I use a third party library called FluentValidation https://github.com/JeremySkinner/FluentValidation

Has similarities to your validation 👍

**Comment by LoganWright** [comment]
That's pretty cool @jchannon thoes route constraints look pretty similar to something we use in our routing? ie:

```c#
Get["/user/{id:int}"] = parameters => 
{
    int id = parameters.id;
    return db.GetUserById(id);
}
```

Here, `id` will be `Int`

```Swift
app.get("user", Int.self) { request, id in 
    return try User.findOne("id" == id)
}
```

**Comment by jchannon** [comment]
What happens if you call it with /user/bob, does it 404?

**Comment by jchannon** [comment]
Ooh this might please you too
https://github.com/apple/swift-evolution/pull/299

**Comment by LoganWright** [comment]
@jchannon That would error out, yup!

And yea, that would definitely please us! If you look at the original proposal, it's actually by @tannernelson

**Comment by LoganWright** [comment]
Closing this to do some cleanup, thanks for the compliments @jchannon 👍
