### ISSUE TITLE
refactor `Valid` rules initialization

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#244]
# Refactor `Valid` so that you define the rules only once during initialization of the containing entity.

* Author(s): [Evertt](https://github.com/Evertt)
* Status: **[Awaiting review](#rationale)**

## Introduction

I want to change this:

```swift
class Post {
    var title: Valid<Count<String>>

    init(request: Request) throws {
        title = try request.data["title"].validated(by: Count.max(5))
    }
}
```

To this:

```swift
class Post {
    let title = Valid(Count<String>.max(5))

    init(request: Request) throws {
        try title.set(request.data["title"])
    }
}
```
## Motivation

Right now you need to provide the valid character count every time you assign to this property. This means you'll be repeating yourself over and over again. And what's worse, if your properties are public then any outsider can make up their own rules about how many characters should go in `title`. I propose to change this so that you define your rules only **once**.

## Proposed solution

See my example code given in the introduction.

## Code snippets

See my example code given in the introduction.

## Impact

This will definitely mean that current Vapor applications that use validation will not compile anymore until they update their code. However, I guess that that's less of an issue since Vapor is still so young and incomplete.

## Alternatives considered

I wouldn't know any alternative other than to not implement this change.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
This is an interesting point. I think one alternative that should be considered is using a `ValidationSuite`. It would work like follows:

```swift
class Title: ValidationSuite {
    static func validate(input value: String) throws {
        let evaluation = Count.max(5)
        try evaluation.validate(input: value)
    }
}
```

```swift
class Post {
    var title: Valid<Title>

    init(request: Request) throws {
        title = try request.data["title"].validated()
    }
}
```

I'm very interested to hear Logan's opinion though since he wrote this feature.

**Comment by LoganWright** [comment]
@Evertt Thanks for the proposal!

How do you feel about adapting a suite similar to what Tanner posted?

The original idea of this, building off of Ben-G's validation library was to create the idea that something like `Valid<Title>` couldn't possibly exist unless it had been validated. This means that if, for example, a function takes `Valid<Title>` as an argument, we know it's an appropriate value before it can even enter the function.

Looking now, I can see some value to composing your models as opposed to creating a suite (ex: `Title` above). With the proposed syntax, `value` would have to be some type of optional or something to encapsulate the possibility that a value doesn't exist. This would require consideration on whether or not we could continue to support the value safety, something I see as very important.

Let me know some of your thoughts on this

**Comment by Evertt** [comment]
> The original idea of this, building off of Ben-G's validation library was to create the idea that something like `Valid<Title>` couldn't possibly exist unless it had been validated. This means that if, for example, a function takes `Valid<Title>` as an argument, we know it's an appropriate value before it can even enter the function.

Hmm yes that does sound nice and valuable. And you know what, I'm guessing that might even still be possible. If we give `Valid` an associated `ValidatorType` type which **does** need to be validated on initialization. That could work, right? Then the function would look like this:

```swift
func foo(bar: Valid<Title>.ValidatorType) {
    // if we reach this line then bar is guaranteed to be valid
}
```

What do you think?

**Comment by Evertt** [comment]
@LoganWright I'm more and more starting to think that the way you made it is the best it can be. It provides a way to validate even function arguments directly **and** it doesn't have to have the issue that I described if you make `ValidationSuite`s.

**Comment by Evertt** [comment]
After much thinking I no longer stand by my proposal, because I think it adds more problems than it solves. So I'm closing this issue, but feel free to reopen it if anyone wants it to be reconsidered.

**Comment by LoganWright** [comment]
Hi @Evertt 

Works for me, if you give it more thought and come up with something you think is awesome, definitely share it and we can reopen! It's also here in history in case someone else wants to come in and open it up.

Thanks so much for participating in Vapor!
