### ISSUE TITLE
Some useful alogrithm testing in Vapor suite

### ISSUE THREAD

**Issue by proyb6** [qutheory/vapor#245]
https://github.com/hollance/swift-algorithm-club

**Comment by LoganWright** [comment]
Hi @proyb6,

I love that repo, a lot of really awesome stuff on there! I'm not quite sure what this issue is asking for though, would you mind clarifying a bit?

**Comment by proyb6** [comment]
I've forgotten this submission. Sorry that I didn't clarify, the test suites is awesome and easier to explain with some images that we'll get the ideas how alogrithm works before reading the code:
https://github.com/raywenderlich/swift-algorithm-club/tree/master/Binary%20Search%20Tree

This should helps Vapor test suite providing a clear view without understanding Vapor internal architecture and get feedback if the test failed.

**Comment by LoganWright** [comment]
@proyb6 awesome stuff in that repo, and thanks for filing an issue for us to discuss. Improving the clarity of our documentation helps users be successful and is great to keep in mind. 

I'm going to close this in preference of #292 which is a bit more defined at the moment. We can talk further there about some good Vapor explanations.
