### ISSUE TITLE
rename `And` and `Or` validators to `Both` and `Either`

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#246]
# Rename `And` and `Or` validators to `Both` and `Either`

* Author(s): [Evertt](https://github.com/Evertt)
* Status: **[Approved](#rationale)**

## <a name="introduction"></a> Introduction

I want to change this:

```swift
var property: Valid<Or<OnlyAlphanumeric, Email>>
```

To this:

```swift
var property: Valid<Either<OnlyAlphanumeric, Email>>
```
## Motivation

Because I find it more readable.

## Proposed solution

See code in the [introduction section](#introduction).

## Code snippets

See code in the [introduction section](#introduction).

## Impact

It will impact projects that use the `And` or `Or` validators directly instead of using the operators. They will need to update their code.

## Alternatives considered

Other than not implementing this proposal I can also imagine one could replace `Or` with `OneOf`. I prefer `Either` though, because I still think it's the most readable and I prefer one word over two.

## Decision (For Moderator Use)

On May 18, 2016, the community decided to implement this proposal. The support for this proposal has been good, the work load is low, and the readability is more expressive.

**Comment by LoganWright** [comment]
Hi @Evertt,

Loving all the participation on the validation stuff!

As we discuss this, I want to point out some of the original reason we kept the names `And` as well as `Or` which was it is traditionally used in logical operators such as `left && right` or `left || right`.

With that said, I think it's an interesting approach that clarifies it a bit more. Particularly w/ the way it reads left to right. For example, in our syntax it is closer to `&& left right` which doesn't read quite as logically as `both left right`.

We should also consider that `&&` would return a `Both`

```
let both: Both<Count<String>, OnlyAlphanumeric> =  Count.min(5) && OnlyAlphanumeric.self
```

I think I'm comfortable with the logical statement of `Both Count and Alphanumeric = Count min 5 _and_ only alphanumeric`

Any other thoughts out there?

**Comment by tannernelson** [comment]
+1 `Valid<Either<OnlyAlphanumeric, Email>>` is a lot more readable to me.
