### ISSUE TITLE
allow validators to transform the input

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#247]
# Allow validators to transform the input

* Author(s): [Evertt](https://github.com/Evertt)
* Status: **[Awaiting review](#rationale)**

## Introduction

Right now the `validate(input: String)` methods of `Validator`s only throw when validation fails and never return anything. I want to change that so that the `validate(input: String)` method **either** throws when validation fails **or** returns the validated and possibly transformed input.

## Motivation

There are times when you really want to transform an input to make it more correct or more valid. For example, when a visitor on your website fills in a date on a form. That date is then sent to the backend as a string, but in your model you would really like to have a real (NS)Date object. In that case it would be very nice if the validator did that work for you.

## Proposed solution

That's why I propose to change `validate` methods so that they return values. And then those returned values are considered to be the validated values. That also means that the `tested()` method on `Validatable` needs to change so that it doesn't return `self`, but instead returns the return value of the validator. Same goes for the `validated()` method on `Validatable`.

## Code snippets

The implementation of the validator would look like this:

```swift
import Foundation

public struct Date: ValidationSuite {
    public static func validate(input value: String) throws -> NSDate {
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"

        if let date = dateFormatter.dateFromString(value) {
            return date
        } else {
            throw error(with: value)
        }
    }
}
```

And the usage of that validator would look like this:

```swift
let validDate: Valid<Date> = try request.data["date"].validated()
// validDate.value is now of type NSDate
```

## Impact

Validators will need to be rewritten to accommodate this change. The api calls / use of validators don't change though.

## Alternatives considered

One alternative I can think of is to use a totally different class for transforming valid user input. That would maybe better fit the Single Responsibility Principle, but it brings along more hassle.

If someone would be able to split this validation and transforming into two different packages without adding a lot of extra hassle to using them both then I would be interested.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
Seems like there would need to be an `OutputType` of some sort.

This is what the protocol looks like right now:

```swift
public protocol Validator {
    associatedtype InputType: Validatable
    func validate(input value: InputType) throws
}
```

It would be really cool if code like this could work:

```swift
let date: Valid<Date> = try "May 13th, 2016".validated()
print(date.value) // NSDate
```

It's worth considering, though, if belongs in validation or could belong in a different step of content negotiation or data mapping.

**Comment by Evertt** [comment]
Do more people want to voice their opinion? I'm eager to start working on this.

I'm not sure yet which option would be better:

1. Integrate it in the validator by simply returning the transformed value. I like this option for its ease of use.
2. Making it a separate step and a separate class. I like this option for its conformance to the Single Responsibility Principle.

**Comment by millman82** [comment]
Option 2 seems better.  Primarily to adhere to SRP as you said.  Also, I firmly believe validators have no business changing your data.

**Comment by LoganWright** [comment]
It seems like through discussion we've kind of agreed that transformation is a different step in the process. Perhaps we can open up a new thread at some point to discuss an api that might alleviate that. For now, I'm closing this proposal as not implementing. If there's support to reopen later or we have some new information/capabilities, we can discuss more.

Thanks @millman82 @Evertt for participating in the discussion 👍  looking forward to future proposals!

**Comment by millman82** [comment]
Glad I could provide some help with the direction. I hope my second sentence didn't come off too terse as that was not my intent. I just think validation should be pass or fail with appropriate custom messaging to guide the user toward a resolution.

I believe a potential use for transformation could be for service versioning if using the framework to develop a set of RESTful APIs. If say supporting legacy V1 calls after the contract had changed for example.  Again this would be a separate module though.
