### ISSUE TITLE
`passes()` vs `passed()` in the docs

### ISSUE THREAD

**Issue by Eldorado234** [qutheory/vapor#249]
Hey,

looks like a great project. Just found a small typo. In the [validation docs](https://vapor.readme.io/docs/validation#testing-validity) there is `passes()` used correctly in the code box but the text references the function as `passed()`. Searched for a way to update this myself, but it seems there is not GitHub Repo for the docs?

Cheers

**Comment by LoganWright** [comment]
@Eldorado234 Thanks for spotting it! In the future, if you come across that, at the top of the page, there's a `suggested edits` button. It does require a readme.io account though.

Otherwise, ping us here and we'll get it updated!

Thanks. I'll close this when docs have gone through.
