### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by kerunaru** [qutheory/vapor#251]
# I18n support

* Author(s): [juanma cabello](https://github.com/kerunaru)
* Status: **[Approved](#rationale)**

## Introduction

I don't think this feature needs an introduction actually; all of us know what internationalization is and why it's important for Vapor to support it. Anyway, in case this paragraph is mandatory: Vapor needs to support internationalization in order to become the greatest Swift based web framework. 😄

## Motivation

One of the key features of every professional web framework is the I18n support. Right now Vapor lacks this feature and I think adding this we can make Vapor to be one step closer to the level of others web frameworks around the web.

## Proposed solution

I believe the best place for the dictionaries is under the `Resources/Locales` folder. The structure to be used to separate each language is quite simple: a folder with the language code (`es`, `en`, `jp`, etc.) and as much files as the developer wants to organise its dictionaries under those folders.

As Vapor has JSON format config files already, I propose to use this file format to store the dictionaries, so we can read them natively.

An I18n class is going to take care about locales and site language switching.

## Code snippets

I propose the `static func t(_: String)` method to do the translation of the key passed as argument.

```swift
I18n.t('foo.bar')
```

As you can see it's quite straightforward. That method just search for the key in the corresponding locale folder.

The `static func changeLanguage(_: String)` method will change the current selected locale to the language code passed as parameter in the call.

```swift
I18n.changeLanguage('en')
```

## Impact

As I18n class is quite atomic I don't expect any impact to Vapor applications.

## Alternatives considered

I think about using yaml instead json due to the vast use of yaml format in web frameworks but json is natively supported by Swift so Vapor get less dependencies to third party libraries this way.

## Decision (For Moderator Use)

On **May 26th, 2016**, the community decided to **approve** this proposal.

**Comment by ketzusaka** [comment]
I do worry about static methods. Race conditions could occur where different requests come in at the same time and want different languages. I feel each request should have language information tied to it and passed into internationalization methods.

**Comment by tannernelson** [comment]
We could do `app.i18n` or `app.localization`.

**Comment by ketzusaka** [comment]
The issue with being at the app level is you want to be able to localize responses based on the information provided from each request.

**Comment by kerunaru** [comment]
I like `app.localization`; it's more human readable and I think it has more sense to place a translation method there.

Is the I18n class behind the scene when you call that `localization` method? Or is the Application class taking the responsibility about this?

**Comment by tannernelson** [comment]
I believe we would initialize an `I18n` class on the `app` when it boots. That way the dictionaries could be cached or at least ready to be accessed.

From there we could have something like `app.localization(for: request, at: key)`. Then we could apply a helper method to Request that would be `request.localization(for: key)` that calls the application's localization method and passes itself as the request.

**Comment by ketzusaka** [comment]
@tannernelson yeah that sounds good.

**Comment by kerunaru** [comment]
Ok! So, if nobody has more suggestion I'm going to start the implementation. :)

**Comment by Evertt** [comment]
Well yes I have one more question. Could we use just swift dictionaries instead of json? And if so, would that be preferable since that doesn't need to be parsed?

**Comment by alomvar** [comment]
But that would result in the necessity to recompile the application for every localization change?

@kerunaru I challenge the use of YAML. It is just introducing another format and additional complexity (if necessary though, rather use [XLIFF](https://en.wikipedia.org/wiki/XLIFF) or similar established standard). As with many things YAML (but also Bootstrap, Wordpress and Coca-Cola) is not the best choice just because most people use it. 😁 Correct me, if I am wrong, but it would only define syntax instead of structure, too.

**Comment by kerunaru** [comment]
@alomvar Well… I like the use of standarized formats. We have NSXMLParser for this kind of stuff, so we could have XML files instead JSON.

**Comment by Evertt** [comment]
> But that would result in the necessity to recompile the application for every localization change?

I'm not sure it would if you'd do something like this:

```swift
// Resources/Locales/en/profiles.swift
translations["en"]["profiles"] = [
    "delete_confirmation": "Are you sure you want to delete your profile?"
]



// Resources/Locales/nl/profiles.swift
translations["nl"]["profiles"] = [
    "delete_confirmation": "Weet u zeker dat u uw profiel wilt verwijderen?"
]
```

**Comment by tannernelson** [comment]
I'd like to see JSON files. We already use those for configuration so they would be welcome. Additionally, like @kerunaru touched on, I'm sure the localization would convert to generic `StructuredData` or something similar in which case an XML parser or likewise could be swapped in for those who prefer different formats.

**Comment by kerunaru** [comment]
Should we support both at the very beginning?

**Comment by tannernelson** [comment]
@kerunaru I'd vote for only supporting JSON officially. (As long as it's possible to build support for other data formats)

**Comment by LoganWright** [comment]
How do people feel about implementing a syntax similar to config so we can have continuity between all of our data type accessors.

Syntax would be something like:

```Swift
guard let text = localization["en", "enter-text"].string else { ... }
```

If we want to say that localizations should just be strings, we could also return a string, either optional, or ?? ""


```Swift
let text = localization["en", "enter-text"]
```

Or possibly if we want to create a language code file, but this could be a little limiting initially.

```Swift
let text = localization[.en, "enter-text"]
```

I think I prefer the second syntax returning `""` if the key is `nil`, thoughts on this?

**Comment by kerunaru** [comment]
I was thinking about returning something like "Missing translation for key putyour.keyhere" if the translation is not found… I like the second syntax too, btw

**Comment by LoganWright** [comment]
Made a quick implementation just to test out what it would take here: #317 

It's pretty basic, so we might want to just use it as a starting point. Then again, it might be enough for a simple core.

Could also protocalize `LocalizationDriver` so third party localizations are easier to work with.

**Comment by kerunaru** [comment]
+1 to your proposal. I like leaving the localisation system open, so users could implement it the way they want. People this way could use custom classes to implement whatever file type they need for translations if JSON is not what they use.

**Comment by LoganWright** [comment]
@kerunaru did you start an implementation of some of this stuff in a way that the two of us could join forces? I'll start working on an abstraction now, so if you have input on how that should look as well :)

**Comment by kerunaru** [comment]
@LoganWright nope, I was waiting to define a little more the specs. I think we can start with the current requirements actually. Any working plan? 😁

**Comment by LoganWright** [comment]
Check out the PR here to see what I've got started: #317
