### ISSUE TITLE
mustache character encoding

### ISSUE THREAD

**Issue by OHeroJ** [qutheory/vapor#254]
when i use  
 
	let provider = VaporZewoMustache.Provider(withIncludes: [
	    "admin_navbar": "admin/partials/navbar.mustache",
	     "admin_errors": "admin/partials/errors.mustache",
	     "admin_success": "admin/partials/success.mustache",
	     "admin_layout": "admin/layout.mustache",
	     "blog_page_nav": "blog/partials/page-nav.mustache",
	])
	
project run  well , but ,when use 

	let provider = VaporZewoMustache.Provider(withIncludes: [
	     "admin_navbar": "admin/partials/navbar.mustache",
	     "admin_errors": "admin/partials/errors.mustache",
	     "admin_success": "admin/partials/success.mustache",
	     "admin_layout": "admin/layout.mustache",
	     "blog_page_nav": "blog/partials/page-nav.mustache",
	    "blog_page_footer": "blog/partials/page-footer.mustache",
	])

and   **page-footer.mustache**  : 

	<hr>
	<footer>
	    <div class="container">
	        <div class="row">
	            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                <p class="copyright">Copyright © oheroj</p>
	            </div>
	        </div>
	    </div>
	</footer>

the error location in   **VaporZewoMustache.swift** line 22 :
 
	public init(files: [String: String] = [:]) {
	        includes = [:]
	
	        for (name, file) in files {
	            do {
	                let bytes = try readBytesFromFile(path: file)
	
	                var signedData = bytes.map { byte in
	                    return Int8(byte)    // the error happen , the    po byte ====> 194    ( the overflow)
	                }
	
	                signedData.append(0)
	                includes[name] = String(validatingUTF8: signedData)
	            } catch {
	                Log.warning("Could not open file \(file). Error: \(error)")        
	            }
	        }
	    }

so, i think **Int8**  might be "UInt8"

**Comment by OHeroJ** [comment]
when i change `page-footer.mustache`:

	<hr>
	<footer>
	    <div class="container">
	        <div class="row">
	            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                <p class="copyright">Copyright oheroj</p>
	            </div>
	        </div>
	    </div>
	</footer>
	
if  `<p class="copyright">Copyright © oheroj</p>` no have ` ©`, run well.

**Comment by LoganWright** [comment]
I was able to fix the issue with this:

```Swift
    public init(files: [String: String] = [:]) {
        includes = [:]

        for (name, file) in files {
            do {
                #if os(Linux)
                let bytes = try readBytesFromFile(path: file)

                var signedData = bytes.map { byte in
                    return Int8(byte)
                }

                signedData.append(0)
                includes[name] = String(validatingUTF8: signedData)
                #else
                includes[name] = try String(contentsOfFile: file)
                #endif
            } catch {
                Log.warning("Could not open file \(file). Error: \(error)")
            }
        }
    }
```

Can you confirm if this fixes your issue @OHeroJ

**Comment by tannernelson** [comment]
I created a PR for this in the Vapor Zewo Mustache repo.
