### ISSUE TITLE
OPTIONS support on controllers

### ISSUE THREAD

**Issue by sarbogast** [qutheory/vapor#255]
# Default controller OPTIONS handler

* Author(s): [Sebastien Arbogast](https://github.com/sarbogast)
* Status: **[Approved](#rationale)**

## Introduction

According to [this article](http://zacstewart.com/2012/04/14/http-options-method.html), OPTIONS should be used more. And indeed more and more clients assume it's there, including tests for todobackend.com for example.
In a controller it would be fairly easy to provide a default handler for this OPTIONS verb that could simply return a status 200 and a Allow header that lists all the supported methods.

## Decision (For Moderator Use)

On *May 25th, 2016**, the community decided to **approve** this proposal. HTTP OPTIONS calls are a great way to provide more information about a RESTful resource to consumers of an API. Vapor should make it easy for APIs to take advantage of this.

**Comment by tannernelson** [comment]
This is interesting. So if you had a resource `/users` which has

- `/users` GET, POST
- `/users/:id` GET, PUT, POST

Would we just be providing OPTIONS for `/users`?

**Comment by sarbogast** [comment]
I think we should provide OPTIONS responses for all supported paths, so for both /users and /users/:id

**Comment by Evertt** [comment]
I got convinced by the awesomeness of OPTIONS when I read [this article](http://zacstewart.com/2012/04/14/http-options-method.html). So I'm just leaving it here for other people.

**Comment by tannernelson** [comment]
Approved this for the `0.10` release.

**Comment by tannernelson** [comment]
Solved in #346
