### ISSUE TITLE
client

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor#262]
# Client

* Author(s): [Tanner](https://github.com/tannernelson)

## Introduction

The client helper will allow Vapor applications to communicate with other APIs or services. 

## Motivation

APIs frequently need to use or post data to other services. 

## Proposed solution

Add a client helper on the `Application` class that wraps VeniceX/HTTPClient or NSURLSession in the future.

## Code snippets

```swift
app.client.get("http://google.com", ["q": "test"]) { response in
    switch response {
        case .Success(let response):
            print("Response: \(response)")
        case .Error(let message):
            print("Uh oh: \(message)")
    }

    do {
        let response = try response.extract()
        print("Response: \(response)")
    } catch {
        print("Uh oh: \(error)")
    }

    let response = try? response.extract()
    print("Response?: \(response)")
}
```

## Impact

This only adds functionality.

## Alternatives considered

Using only a closure for getting the response value was considered, but the `.extract()` method gives all possibly desired functionality.

**Comment by NathanFlurry** [comment]
I know this is already approved, but I'd like to make a counterproposal. I'd like to make this client library something that is very dynamic and reuses as much code as possible. I also think this library should be a separate repository than Vapor, but integrates with it very well. Maybe call it something like Condensation or Deposition. 😉

* * *

Initially, the library would look a lot like Alamofire by having requests like:
```swift
Client.get("http://url.com/hello/world").success { request, response in
    
    }.failure { request, response in
        
    }.run()
```

* * *

However, where it begins being unique is having the ability to use conditionals to deal with responses. For example, to use conditionals to have different success callbacks for different response codes, one would code this:
```swift
let request = Client.get("http://url.com/hello/world")
    .condition({ request, response in return response.code == 204 }) { request in
        request.success { request, response in }
    }.condition({ return $1.headers[.Connection: "keep-alive"] ) { request in
        request.success { request, response in }
        request.failure { request, response in }
    }.success { request, response in // If none of the above conditions are true, run this
        
    }.failure { request, response in
        
    }.run()
```


* * *

Another key concept for this framework is being able to build requests off each other. For instance, say we make a base request like so:
```swift
let base = Client.base("http://url.com/").headers([.UserAgent: "Vapor"]).params(["api-key": "abc"]).auth(/* Some stuff */)
```
We can then make a request to `http://url.com/hello/world` by using the base request and sharing the headers and parameters like this:
```swift
base.get("hello/world").success { request, response in
    
    }.failure { request, response in
        
    }.run()
```
One can even create an endpoint base off another endpoint base like this:
```swift
let helloBase = base.base("hello")
helloBase.get("world").run()
```
One can then build a hierarchy of endpoints like this:
```swift
struct Endpoints {
    static let base = // Same as above
    static let helloWorld = base.get("hello/world").response { request, response in
        
    }
    static let apiTest = base.get("api/test").response { request, response in
        
    }
    
    struct Base {
        static let base = Endpoints.base.base("/some-base")
        static let someOtherEndpoint = base.get("some-endpoint").response { request, response in
            
        }
    }
}
```
Then developers can easily access any of their preconfigured endpoints like this:
```swift
Endpoints.helloWorld.run()
Endpoints.Base.someOtherEndpoint.run()
```

* * *

However, that's just scratching the surface. Another handy feature would be the ability to overwrite properties of the base endpoint, like this:
```swift
let base = Client.get("http://url.com/hello/world").params(["test1": "abc", "test2": 123, "test3": true])
base.params(["test1": "def", "test2": nil]).run()
```
Executing this code would send a request with the parameters of `["test1": "def", "test3": true]`. Setting the `test2` key to nil removed the key completely. This would theoretically work with any other value too.

* * *

Then, there's the ability to insert variables into request parameters. For instance, one could execute...
```swift
let base = Client.get("http://url.com/search/{search-key}").params(["page": "{page-num}", "result-count": 10])
base.vars(["search-key": "hello world!", "page-num": 5]).run()
```
...which would send a request to the URL `http://url.com/search/hello%20world!` with the parameters `["page": 5, "result-count": 10]`.

* * *

In addition, one would be able to chain success blocks like so:
```swift
Client.get("http://url.com/hello/world").success { request, response, next in
        if /* something wrong with data */ {
            throw Error("Oh no!") // Goes to `error` callback
        } else {
            next() // Goes to next `success` callback, there could be many chained success callbacks in a row
        }
    }.success { request, response in
        // Do something else with the data
    }.failure { request, response in
        // Only a request failure, like a 404
    }.error { error in
        // An actual error thrown
    }.run()
```

* * *

Finally, the library would be able to cast responses into Swift serializable objects. This would make it possible to share objects between Vapor and clients.
```swift
endpoint
    .success(User.self, dataSource: .body) { user in /* Do something with the user */ }
    .failure(RequestFailure.self, dataSource: .body) { requestFailure in /* Do something with the failure */ }
    .error { error, request, response in
        // Error casting User or Error
    }.run()
```
The `dataSource` property would define where the data for the object comes from, such as a JSON body or the parameters.
Notice that you can still retrieve the request and response variables if needed or exclude them if necessary.
In addition, response bodies are automatically casted into their respective datatypes, like JSON or images. For instance, one could get the JSON data by saying this:
```swift
endpoint
    .success { request, response in
        if let json = response.data as? JSON {
        /* or */
        if let json = JSON(data: response.rawData) {
            
        }
    }.failure { request, response in }
    .run()
```
However, using the ability to automatically cast data into data types, one could do this in a much more elegant fashion like this:
```swift
endpoint
    .success(JSON.self) { json in /* Do do something with the JSON */ }
    .failure(XML.self) { xml in /* Do somethign with the XML */ }
    .run()
```

* * *

I could go on, but I think I've written enough to give you a good idea of what I'm talking about. I started [implementing this idea](https://github.com/theMonster/KAHN) with someone else about a year ago, but didn't get too far. To reiterate, I think that this would be a good project to put in a separate repository.
