### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor#268]
Implement web sockets.

**Comment by proyb6** [comment]
It was appeared on HackerNews few days ago for Node.js and C++
https://github.com/alexhultman/uWebSockets

It's worth a benchmark against uws or integrate uws into Vapor!

**Comment by tannernelson** [comment]
Unfortunately Swift cannot interface with C++. Hopefully that will come in the future.

**Comment by tannernelson** [comment]
Delaying this until https://github.com/Zewo/WebSocket passes autobahn.

**Comment by tannernelson** [comment]
Implemented! 🎉

**Comment by wildfiremedia** [comment]
How do we use WebSocket without any info in documentations?

**Comment by LoganWright** [comment]
@wildfiremedia for now, some examples will probably be good:

https://github.com/vapor/slack-bot

https://github.com/vapor/engine/blob/master/Sources/WebSocketsExample/main.swift

We'll make sure to detail more thoroughly in docs.
