### ISSUE TITLE
StringInitializable in `add` on Application

### ISSUE THREAD

**Issue by Joannis** [qutheory/vapor#273]
# StringInitializable routes in Application with a method variable

* Author(s): [Joannis](https://github.com/Joannis)

## Introduction

Currently we can use StringInitializable with the `.get`, `.put`, `.post` and `.delete` on `Application`. However when a method isn't specified yet whilst I want to use `StringInitializable`.

## Motivation

I'm building an API that makes use of Models to generate routes. Similar to Zewo Resources but in a more Vapor-style. The problem that I found was that when I created a tuple

## Proposed solution

Adding the `StringInitializable` methods to the `.add` function would allow us to specify dynamically which method we want to use without having an impact on existing applications.

## Code snippets

```swift
for handle in H.objectHandlers.handlers {
    switch handle.method {
    case .get:
        app.get(handle.action, H.S.self) { request, object in
             return try handle.handler(context: .rest(request), object: object).jsonValue
        }
    case .post:
        app.delete(handle.action, H.S.self) { request, object in
            return try handle.handler(context: .rest(request), object: object).jsonValue
       }
    case .put:
       app.put(handle.action) { request in
           return try handle.handler(context: .rest(request), object: nil).jsonValue
       }
    case .delete:
        app.delete(handle.action, H.S.self) { request, object in
            return try handle.handler(context: .rest(request), object: object).jsonValue
        }
    default:
        return
    }
}
```

Would be reduced to

```swift
for handle in H.objectHandlers.handlers {
    app.add(handle.method, handle.action, H.S.self) { request, object in
         return try handle.handler(context: .rest(request), object: object).jsonValue
    }
}
```

**Comment by tannernelson** [comment]
We have this:

```swift
public final func add(_ method: Request.Method, path: String, handler: Route.Handler) { ...
```

Is there something about this one that needs to be changed?

**Comment by Joannis** [comment]
It doesn't accept `StringInitializable` like `get` `post` `put` and `delete` do.

**Comment by tannernelson** [comment]
Oh okay, is `handle.action` `StringInitializable`?

That shouldn't be too hard to add, I'll look into it.

**Comment by Joannis** [comment]
`handle.action` would be the method.
`H.S.self` would be `StringInitializable`

I should've clarified that :P

**Comment by LoganWright** [comment]
I think this would require adding the add function to the generator to account for all cases, and might end up being a little complex. 

The more concise syntax is pretty nice, so I'd say it's a feature we'd like to include, even if it's not immediately prioritized.

**Comment by Joannis** [comment]
This ticket should be closed I think. I don't think it's relevant

**Comment by tannernelson** [comment]
I think with the updated routing we have this will be a lot better.
