### ISSUE TITLE
Better way to handle large groupings of routes

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#274]
# Feature, Enhancement, or Optimization

# RouteGrouping

* Status: **[Approved](#rationale)**

## Introduction

A structure or syntax to facilitate the generation of more complex routes in an easier manner.

## Motivation

When dealing with fully featured enterprise applications, there needs to be a more efficient way to organize large groupings of routes beyond just controller.

## Proposed solution

Two solutions have been proposed.

### 1. return grouped application objects that can be extended separately.

```Swift
let app = Application()
let usersGroup = app.grouped("users")
```

Which could then be used like so:

```Swift
usersGroup.get("repos") { req in ... }
usersGroup.get("starred-repos") { req in }
```

Groups could also be further extended:

```Swift
let userMessages = usersGroup.group("messages")
userMessages.get("unread") { req in ... }
userMessages.post("new") { req in ... }
```

##### Possible future

```Swift
// middleware etc...
let groupedByMiddleware = users.group(SomeMiddleware)
```

### 2. New Type

This would be some type of new grouped route type for the purposes of this, we'll temporarily refer to as `Group`

```
class UsersRoutes: RouteGroup {
    static func register(app: Application) {
        app.get("/") {
            // blah index
        }
        app.post("/") {
            // blah store
        }
    }
}

app.group("users", UsersRoutes)
app.group("users") {
    app.get("/") {
        // blah index
    }
    app.post("/") {
        // blah store
    }
}

extension Application {
    func group(path: String, routes: RouteGroupConvertible) {
        ...
    }
}
```

## Impact

Depending which way we go, it might impact existing code, but I don't see either as very invasive to existing architecture.

## Alternatives considered

lots and lots of inline routes

## Decision (For Moderator Use)

On **May 25th, 2016**, the community decided to **approve** this proposal. Vapor needs a thread safe and extensible way to perform groupable routing.

**Comment by NathanFlurry** [comment]
I feel like using `app.get` inside of a block for a group – as seen in solution 2 – is a bit clumsy and adds the pain of dealing with a stack inside the codebase to know which group you're committing the routes to. I feel the best solution would be to combine both options, but the group itself would be passed into the closure in solution 2 like so:
```swift
app.group("users") { users in
    users.get("/") {
        // blah index
    }
    users.post("/") {
        // blah store
    }
}
```
This would provide the flexibility of passing around a `Group` object for modification and the brevity of the closure approach.
