### ISSUE TITLE
NSDate

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#278]
# Feature, Enhancement, or Optimization

# NSDate Convenience

* Author(s): [Developer](https://github.com/<your-username>)
* Status: **[Awaiting review](#rationale)**

## Introduction

NSDate is now fully implemented, so we get a lot of really great date time features for free. Unfortunately, its apis are sometimes still a bit lacking.

Investigate existing and popular swift nsdate wrappers to see what will work well for Vapor to support

## Motivation

NSDate isn't where it should be in Swift. ex: it doesn't conform to Comparable out of the box.

## Proposed solution

Investigate existing libraries to see what would be required to incorporate as a dependency into Vapor.

## Code snippets

```Swift
let earlier = Date.now() < otherDate
```

```Swift
let stringToPass = date.iso8601String
```

## Impact

n/a

## Alternatives considered

Wrapping c-level time features to fully implement custom date object.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by Evertt** [comment]
Possible packages to consider:

[https://github.com/melvitax/AFDateHelper](https://github.com/melvitax/AFDateHelper)
[https://github.com/al7/SwiftDateExtension](https://github.com/al7/SwiftDateExtension)

And I especially like the API of this one:
[https://github.com/naoty/Timepiece](https://github.com/naoty/Timepiece)

**Comment by tannernelson** [comment]
We are using NSDate in 0.11.

**Comment by Evertt** [comment]
@tannernelson care to explain why that was chosen over for example Timepiece?

**Comment by tannernelson** [comment]
You can still include Timepiece in your project. NSDate is performant and NSDateFormatter does everything we needed for parsing and serializing responses.
