### ISSUE TITLE
How iOS app communicate with vapor by websocket?

### ISSUE THREAD

**Issue by ldbfrank** [qutheory/vapor#2796]
Hi,
I am wondering whether there is special vapor client sdk for iOS?
Or I could use starstream or any websocket sdks to communicate with vapor?

Thanks.

**Comment by mkll** [comment]
@ldbfrank Since websocket is an RFC standard, you can use Starscream or any other library to communicate with Vapor.

**Comment by ldbfrank** [comment]
@mkll Got it! Thanks!
