### ISSUE TITLE
robust cookie support

### ISSUE THREAD

**Issue by ketzusaka** [qutheory/vapor#283]
# Enhancement: Robust Cookie Support

* Author(s): [James Richard](https://github.com/ketzusaka)
* Status: **Approved**

## Introduction

Cookies are an important part of handling sessions and tracking. We should support configuring them to the HTTP standard.

## Motivation

Setting cookies in Vapor is rudimentary in its current form. The only support currently is to give a cookie a name and a value. These limitations can lead to confusing bugs where a cookie can only work in certain locations of a site, and we don't offer any way to work around that. We should support a full set of cookie attributes, such as:

* The ability to specify the domain the cookie applies to
* The ability to specify the path the cookie applies to
* The ability to specify an expiration time for a cookie
* The ability to specify a max age for a cookie
* The ability to specify a cookie as Secure only
* The ability to specify a cookie as HTTP only

## Proposed solution

Defining a cookie should make use of Zewo's [AttributedCookie](https://github.com/Zewo/HTTP/blob/master/Sources/AttributedCookie.swift) type. By using this type we'd get all of the previously listed functionality. This would only apply to the `Response` cookies, as a `Request` wouldn't be interested in or provided this information.

We currently provide cookie setting through a `Dictionary`. I suggest changing this structure to a new type, `Cookies`. This new type would provide a simple API to insert and remove cookies, and to maintain backwards compatibility (and simplicity in setting a cookie) a subscript handler for simple cookie setting.  This type would internally store a `Set<AttributedCookie>`. Using a `Set` over an `Array` would guarantee uniqueness of a cookie name. Note that an `AttributedCookie` is hashed and compared solely on the name, and not any of the other attributes.

In order to make use of the `AttributedCookie` `struct` we would add Zewo/HTTP as a dependency.

## Code snippets

The new `Cookies` type would have a simple public API:

```
public struct Cookies {
    public mutating func insert(_ cookie: AttributedCookie)
    public mutating func remove(_ cookie: AttributedCookie)
    public func contains(_ cookie: AttributedCookie) -> Bool
    public subscript(name: String) -> AttributedCookie? { get set }
}
```

Under the new system managing a cookie could look like any of these variations:

```
response.cookies.insert(AttributedCookie(name: "Foo", value: "Bar"))
response.cookies.remove(AttributedCookie(name: "Foo", value: "Bar"))
response.cookies["Foo"] = "Bar"
response.cookies["Foo"] = nil
```

Inserting a cookie using the subscript would apply it to the full domain path. This will alleviate confusion for our users if they set a cookie in one location and it isn't present elsewhere. For example, setting a session at `/channels/ketzusaka` would set the cookie path to be `/`, and not `/channels`.

## Impact

This will be a breaking change for any codebase currently using the response cookies dictionary in ways other than subscripting. Since most cookie operations are subscripts, and the new `Cookies` type provides the same API as a `Dictionary` subscripting, I feel this will not affect many people.

## Alternatives considered

I considered copying the `AttributedCookie` type into our codebase. I'm not sure if thats something we want to do given our history with cloning code into the repository, but I do worry about dependency bloat as we adopt single structures from varying sources.

I also considered naming the `Cookies` type something more descriptive, like `ResponseCookies` or `CookieCollection`, but opted for the simplest name. Open to suggestions!

## Decision (For Moderator Use)

On **May 20th, 2016**, the community decided to **approve** this proposal. Robust cookie support is necessary for modern frameworks.

**Comment by tannernelson** [comment]
All of this looks great. I especially like the subscripting: 

```swift
response.cookies["Foo"] = "Bar"
response.cookies["Foo"] = nil
```

If we bring in `AttributedCookie` we should not use `@__export` and instead `typealias` it. This also gives us a chance to rename it to just `Cookie` which I think is better.

**Comment by LoganWright** [comment]
@ketzusaka great proposal, I think more advanced cookies would be a great feature 👍 

I do have some concerns around including the HTTP dependency that will prevent us from including it in its entirety. There are several extensions on objects that we also have extensions for where the zewo extensions may not be compatible with Vapor behavior and could cause confusion in the Vapor code base.

The main part though is the underlying C dependencies down the tree. 

We should approach zewo about a few possibilities. Isolating attributed cookies, moving it to S4, or integrating the file directly into Vapor w/ associated zewo licensing.

**Comment by ketzusaka** [comment]
I agree @LoganWright. Maybe copying it over and then working with S4 to get it integrated is the best approach for this.

@tannernelson `Cookie` sounds good to me. My only concern is people might expect that to be the value of the `Request` cookies, which should continue to just be a `[String: String]` imo

**Comment by tannernelson** [comment]
I think it's possible that one will need information such as `path` or `secure` from even the cookies that they receive in the `Request`. Also I don't think devs will be interfacing much with cookies directly so it doesn't need to have a simple `[String: String]` API. It will probably be mostly middleware interfacing with both request and response cookies.

**Comment by ketzusaka** [comment]
My understanding of how Cookies work is that the client will not send information about the attributes of a previously set cookie (such as path and secure). We'd have to store that somewhere for the user, and I don't think thats something we should do.

**Comment by tannernelson** [comment]
Oh okay, I haven't read the RFC or anything for cookies. If the client just sends the string, then that's perfect.

**Comment by tannernelson** [comment]
This has been added to S4 0.9

**Comment by LoganWright** [comment]
This has since been removed from S4, but we have native support in Vapor. Feel free to reopen if something is unsatisfactory!
