### ISSUE TITLE
Range support can send negative content-lengths

### ISSUE THREAD

**Issue by weissi** [qutheory/vapor#2837]
The HTTP range support has some problems with a bunch of illegal ranges. Consider this example

```
$ { echo -e 'GET /random_10m HTTP/1.1\r\nhost: localhost\r\nrange: bytes=9223372036854775807-0\r\n\r\n'; sleep 10; } | nc localhost 8080
HTTP/1.1 206 Partial Content
etag: 1653486270.514997-10485760
accept: bytes
content-range: bytes 9223372036854775807-0/10485760
content-length: -9223372036854775806
connection: keep-alive
date: Thu, 26 May 2022 15:35:18 GMT


```

- `content-length: -9223372036854775806` is malformed HTTP. 
- `content-range: bytes 9223372036854775807-0/10485760` is also malformed in multiple ways
    - begin > end
    - begin > total file size
    - `content-length` != the number of bytes announced by the (malformed) `content-range`.

The Vapor app is more or less

```swift
let file = FileMiddleware(publicDirectory: "/tmp/files")
app.middleware.use(file)

try app.run()
```

and the `random_10m` file is just a random file with 10 MiB of random data, something like `dd if=/dev/urandom of=/tmp/files/random_10m bs=1m count=10`

Vapor version: 4.60.2

**Comment by 0xTim** [comment]
Fixed in 4.60.3
