### ISSUE TITLE
Add Heroku Instance to Build Pushes

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#286]
# Setup heroku web hooks

* Author(s): [Developer](https://github.com/logmaestro)
* Status: **[Awaiting review](#rationale)**

## Introduction

Heroku is a highly popular, free starter, and easy to use server solution that we've committed to supporting. This proposes that we setup an instance to build master and if possible PRs so that we can be confident deploys are working.

Ideally in future, we'd automate this behavior on multiple server platforms.

## Motivation

Allows us to quantify current Heroku status. Will hopefully encourage server automations so we can make it as easy to check status.

## Proposed solution

Set it up for master and investigate PRs

## Code snippets

n/a

## Impact

It will be able to be deployed to Heroku more confidently.

## Alternatives considered

--

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
Does this mean adding Heroku to the travis file or is this a separate service?

**Comment by LoganWright** [comment]
It's a separate tool, building master is easy, to build prs we need to commit a config file, that's why I held off temporarily.

**Comment by LoganWright** [comment]
This is now included in master. PRs will build on generated urls, master will be visible here: https://vapor-build.herokuapp.com
