### ISSUE TITLE
messages on `Abort`

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor#295]
Add messages to the Abort errors.

**Comment by LoganWright** [comment]
This seems to already be done?

https://github.com/qutheory/vapor/blob/7945e81885ee5fc9feeb63c481e21a3c3471128f/Sources/Vapor/Middleware/AbortMiddleware.swift#L24

Is this referring to something else?

**Comment by tannernelson** [comment]
There can't be default arguments so it would require all `Abort.badRequest` to change to `Abort.badRequest(nil)`.

I think this isn't worth it.
