### ISSUE TITLE
VM image for running Swift 3 and Vapor

### ISSUE THREAD

**Issue by proyb6** [qutheory/vapor#299]
Create a Vapor in docker/VM image is useful submitting/troubleshooting code and less work for developers on Windows OS to boot VM and start experiment Vapor web framework.

**Comment by kerunaru** [comment]
I think this is already done https://github.com/qutheory/vapor/pull/300

**Comment by tannernelson** [comment]
Check this out https://twitter.com/qutheory/status/731155381129449474
