### ISSUE TITLE
app.group is not thread-safe

### ISSUE THREAD

**Issue by Danappelxx** [qutheory/vapor#302]
The way [`app.group`](https://github.com/qutheory/vapor/blob/master/Sources/Vapor/Routing/Application%2BRoute.swift#L249-263) is implemented adds state to the application. If the following code is run on many threads many times, eventually the routes will be malformed.

```swift
app.group("a") {
    app.get("b") { _ in ... }
    app.get("c") { _ in ... }
    app.group("d") {
        app.get("e") { _ in ... }
        app.get("f")  { _ in ... }
    }
}
```

**Comment by tannernelson** [comment]
I think the easiest solution here is to add locks.

**Comment by Danappelxx** [comment]
👍
