### ISSUE TITLE
Build / compile error

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#313]
I've tried `vapor clean` and all that kind of stuff, but I can't fix it. One of the packages creates an error during compiling:

```
Compile Swift Module 'C7' (22 sources)
Compile Swift Module 'String' (1 sources)
Compile Swift Module 'PathIndexable' (2 sources)
Compile Swift Module 'Strand' (1 sources)
Compile Swift Module 'CryptoEssentials' (14 sources)
Compile Swift Module 'libc' (1 sources)
/Users/Evert/Sites/vapor/Packages/Strand-1.3.0/Sources/Strand.swift:55:53: error: cannot convert value of type '(arg: UnsafeMutablePointer<Void>?) -> UnsafeMutablePointer<Void>?' to expected argument type '(@convention(c) (UnsafeMutablePointer<Void>!) -> UnsafeMutablePointer<Void>!)!'
                guard pthread_create(&pthread, nil, runner, pointer) == 0 else {
                                                    ^~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a.xctoolchain/usr/bin/swift-build-tool -f /Users/Evert/Sites/vapor/.build/debug.yaml

Make sure you are running Apple Swift version 3.0.
Vapor only supports the latest snapshot.
Run swift --version to check your version.
Error: Could not build project.
```

Does anyone else get that?

**Comment by tannernelson** [comment]
That error is from using `05-09`

**Comment by Evertt** [comment]
Is it though? Because it clearly points to the `05-03` snapshot in the output that I pasted.

**Comment by tannernelson** [comment]
That's really strange. Are you trying to build the framework or an example project that uses the framework?

**Comment by Evertt** [comment]
Just the framework. I merged the latest commits of this master branch into my fork and I'm trying to build that. I even tried switching my snapshots between the two versions, but for some reason it always seems to use the `05-03` snapshot, even if I tell it to use the `05-09` snapshot.

**Comment by tannernelson** [comment]
Master is now building using the `05-09` snapshot. (Just merged some PRs). Make sure you have the latest copy and do a `vapor clean && vapor build`. 

You can also check `swiftenv version` to see which version is being pointed to.

**Comment by Evertt** [comment]
I know I merged those last PRs into my fork as well.

![screen shot 2016-05-25 at 22 49 38](https://cloud.githubusercontent.com/assets/1267282/15555871/0e5b32f2-22cb-11e6-9840-5d69d5103f55.png)

**Comment by Evertt** [comment]
Okay, re-installed the snapshot by downloading it from swift.org and now it works...
