### ISSUE TITLE
Discuss possibility of all CLI Args added to Config as `app`

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#319]
# All CLI Args are put in config as `app`

* Author(s): [Developer](https://github.com/loganwright)
* Status: **[Approved](#rationale)**

## Introduction

Right now if you do `--config:app.port=8080`, we'll set "port" in json file named `app` for access.

What if we just defaulted that, so `--port=9090` would go to `app.port`, but if user wanted custom config, they could do `--config:custom-file-name.customKey=value`. Otherwise, I can't think of a CLI arg that wouldn't be conveniently accessed within config off the top of my head, and it might be more convenient.

## Motivation

Make it a bit easier to interact w/ cli args in config

Possible downside, we might have keys we don't want overridden in the config

## Proposed solution

automate `--name` so its behavior is == `--config:app.name` by default

## Code snippets

`vapor run --port=8080 --host=0.0.0.0`

## Impact

Existing cli using `--config:app.name` would be unaffected.
Old cli args such as work dir would be inside of the config

## Decision (For Moderator Use)

On May 26, 2016, the community decided to accept this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

This is already sort of expected with existing behavior and allows us to maintain old code while providing good convenience access.

**Comment by tannernelson** [comment]
I like this. 👍
