### ISSUE TITLE
Crash on MultiPart Forms

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#321]
# Bugs

If you run Development on #320, visit `localhost:8080/options` in your browser select 2 options at a time, [0,1], [1,2], [2,3], [0,1], [1,2] ... eventually it will crash. the app in a substring file. L148 of String.swift

Output:

> fatal error: cannot increment endIndex

PO Dumps:

self = `"----WebKitFormBoundarya8cyAeA3iUFE0b4w"`
seqString = `"boundary="`

My guess is that it's a 2 parter. One is the string function shouldn't crash, the other is the form shouldn't be submitting/parsed differently (depending on which is the cause).  It's possible we have some lingering state somewhere.

### Visibility

![multipart-crash](https://cloud.githubusercontent.com/assets/5750489/15562316/323ad5c8-22cc-11e6-801a-d6d7e6b3d8ac.gif)

**Comment by tannernelson** [comment]
Can you paste that error output from Xcode?

**Comment by LoganWright** [comment]
fixed in #323
