### ISSUE TITLE
Route hosts the same as groups

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#339]
I saw this in the [documentation](https://vapor.readme.io/docs/routing#host):

```swift
app.host("qutheory.io") {
    app.get("/") { request in
        return "Welcome!"
    }
}
```

But wouldn't that also be better and more thread-safe if it were this:

```swift
app.host("qutheory.io") { qutheory in
    qutheory.get("/") { request in
        return "Welcome!"
    }
}
```

?

**Comment by NathanFlurry** [comment]
I believe this has already been changed. The documentation is long out of date, feel free to commit your own edits.

See #302 and #307.

**Comment by LoganWright** [comment]
Updated documentation.
