### ISSUE TITLE
See Vapor CLI version

### ISSUE THREAD

**Issue by jonathan-top** [qutheory/vapor#350]
Enhancement

Display Vapor CLI version

## Introduction

When using the self-update mechanism it's not clear which version of the Vapor CLI you got with the update.

## Motivation

Due to compatibility issues with minor Swift versions and Vapor version it's very useful to see which exact versions are running on a pc.

## Proposed solution

It would be great to see the version number in both the self-updater and the help function

**Comment by tannernelson** [comment]
This has been covered in qutheory/vapor-cli#23
