### ISSUE TITLE
new app's mustache is broken

### ISSUE THREAD

**Issue by rshev** [qutheory/vapor#371]
hi. done everything as specified at https://vapor.readme.io/docs/hello-world with a correct swift toolchain of course.
new project compiles, runs but has this warning in console:
```
[1465471849] [WARNING] Could not open file ./Resources/Views/Includes/header.mustache. Error: CouldNotOpenFile
```
and everything mustache-related is not working. File does exist at the path it's complaining.

And there is 1 warning during compilation (maybe it's related):
```
VaporHelloWorld/Packages/Vapor-0.10.0/Sources/Vapor/Fixes/FileManager.swift:40:32: warning: result of operator '>=' is unused
                stat(path, &s) >= 0
                ~~~~~~~~~~~~~~ ^  ~
```

**Comment by tannernelson** [comment]
Moved to https://github.com/qutheory/vapor-mustache/pull/9
