### ISSUE TITLE
`readBytesFromFile` does not fail for missing files

### ISSUE THREAD

**Issue by jkubicek** [qutheory/vapor#384]
In class `FileManager` the following method never throws. It should probably throw a `FileManager.Error.CouldNotOpenFile` error when the file does not exist.

```swift
static func readBytesFromFile(_ path: String) throws -> [UInt8] {
    let data = NSData(contentsOfFile: path)
    return data?.byteArray ?? []
}
```

**Comment by tannernelson** [comment]
You're right. Does `contentsOfFile` return `nil` when the file doesn't exist?

**Comment by jkubicek** [comment]
It does.

**Comment by LoganWright** [comment]
Looks like this one is merged in and fixed, thanks @jkubicek
