### ISSUE TITLE
Overflow when casting UInt32.max to Int...

### ISSUE THREAD

**Issue by dgsmith** [qutheory/vapor#409]
# Bugs

Trying to build on a BeagleBone Black with swift 3. All dependencies compile, but in `Linking .build/debug/Generator` I get the error: 
```
/home/debian/server/Packages/Vapor-0.11.1/Sources/Vapor/WebSockets/Model/Frame.swift:357:50: error: integer overflows when converted from 'UInt32' to 'Int'
                let key = UInt32(libc.random() % Int(UInt32.max))
                                                 ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/debian/swift-3.0/usr/bin/swift-build-tool -f /home/debian/server/.build/debug.yaml
```

Shouldn't the line of code just be:
```swift
let key = UInt32(libc.random()) % UInt32.max
```

After changing that line of code, my project compiles, thanks!

**Comment by LoganWright** [comment]
It appears the issue is that Int32 is the max Int on that system, so it's breaking the overflow which makes sense. Would you submit a PR for that patch, or I can add it in today
