### ISSUE TITLE
The slack url is break

### ISSUE THREAD

**Issue by judi0713** [qutheory/vapor#413]
Sorry, but i don't know where the question belong to which part..

## Introduction

The slack url is break,always appear "502 Bad Gateway".

**Comment by timominous** [comment]
@judi0713 is this the one on the Readme?

**Comment by LoganWright** [comment]
It seems to be up for me: http://slack.qutheory.io/

We moved hosting recently to make it more stable, let me know if you're still experiencing problems.

**Comment by judi0713** [comment]
@timominous Year,the image is break,but I just try ,now it's OK!Thank you! @LoganWright @timominous  I will closed this issue!Thank both of you very much!!

**Comment by judi0713** [comment]
Maybe you can fix the image appear.I live in China, but whatever ways I visit the site,the slack image is broken.I use vpn in Japanese it can't appear either.
![screen shot 2016-07-01 at 10 02 16](https://cloud.githubusercontent.com/assets/8736805/16509785/edc7a63c-3f72-11e6-96ae-f59edc501b50.png)

**Comment by LoganWright** [comment]
@judi0713 fixed the badge, thanks for pointing it out 👍
