### ISSUE TITLE
Cryptography best practices

### ISSUE THREAD

**Issue by comex** [qutheory/vapor#42]
I've only taken a quick look at the code, but I see a few theoretical security issues:

- You're using SHA-1 for various purposes; due to recent cryptanalytic breakthroughs on it, it's highly recommended to avoid SHA-1 in favor of SHA-2 or another hash (["SHA-1 is no longer considered secure against well-funded opponents"](https://en.wikipedia.org/wiki/SHA-1)).  If you were using the HMAC construction with `applicationKey`, this would be only a theoretical issue, as the only attack likely to be practical on SHA-1 anytime soon is a collision attack, and HMAC does not depend on collision resistance (and your other use of SHA-1, generating random session IDs, does not benefit from reverse engineering the hash), but...
- ...you're hashing the string `"\(string)\(applicationKey)"`.  Since the data is first and the hash is (essentially) iterative, finding a collision between two legal data strings (which can be done offline) would also cause the concatenated string to collide.  Reversing the order would fix that but open up length extension attacks.  Instead, use HMAC, that's what it's for.
- On Linux, you're generating random numbers using libc's `random`, which is very much not cryptographically secure.  Easiest to just read from `/dev/urandom` instead.  (On OS X, `arc4random` is okay but theoretically vulnerable to issues with bias, with the same solution.)
- While this is unlikely to ever be an issue in practice, the random session generator uses an unnecessarily low amount of entropy, with "only" 100 million possibilities (26 bits) from the two `Int.random` calls.  100 million is high for an online attack and unless the clock is somehow compromised, the precision of `timeIntervalSinceNow` bumps that up by many more orders of magnitude - but avoiding this tiny risk is just a matter of adding a few more zeroes, so it'd be best to do so.  Better yet, just get 16 random bytes from a suitable generator without going through the SHA hashing.

**Comment by tannernelson** [comment]
These are all very valid points. Would you have time to submit a PR that addresses them?

**Comment by elithrar** [comment]
In addition, something like https://github.com/krzyzanowskim/CryptoSwift may help reduce some maintenance/implementation burden.

Boiling it down into two actions: 
 * As @comex touches on, HMAC-SHA-256 would be the way to go for signing cookies 
* Pull 256 bits (32 bytes) from /dev/urandom when you need random bytes. Don't hash it or combine with a timestamp (unless sorting/ordering is a feature you need). base64'ing the output should be enough.

If @comex doesn't have time to pick up the PR I'd be interested, but haven't authored Swift before (plenty of Go, though) so would need to get a dev env. up first.

**Comment by tannernelson** [comment]
CryptoSwift seems like a great option. I'd be very interested to see a PR implementing this. 

Also if you need help setting up a dev environment, we have a lot of smart guys in the Vapor Slack that could help you out wit that.

**Comment by shnhrrsn** [comment]
+1 for CryptoSwift, using it in a different project and it's solid

**Comment by tannernelson** [comment]
Added CryptoSwift to the roadmap https://github.com/qutheory/vapor/wiki/Roadmap
