### ISSUE TITLE
Subscripting JSON doesn't work

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#421]
Because of our PathIndexable, it's ambiguous on JSON for things like `js["key"]`

**Comment by LoganWright** [comment]
I _believe_ this is a result of Value redeclaring Polymorphic requirements when we brought Fluent into the mix

**Comment by LoganWright** [comment]
It's not so much subscripting as chaining it, and appears to be an issue w/ variable declarations in Jay, czech has offered to remove his implementations which will fix the issue in future. For now, workaround is to not access .string directly on JSON object where possible and opt for `data` or `StructuredData`

**Comment by Joannis** [comment]
This isn't relevant anymore, is it?

**Comment by tannernelson** [comment]
Yup, this was fixed with #451
