### ISSUE TITLE
06-20a build error

### ISSUE THREAD

**Issue by jjjjjeffrey** [qutheory/vapor#424]
swift build error like this:
/Vapor-Demo/Packages/CryptoEssentials-0.7.3/Sources/NSData+Extensions.swift:32:45: error: missing argument label 'options:' in call
            return self.base64EncodedString([.encoding64CharacterLineLength])

swift --version
Apple Swift version 3.0-dev (LLVM c191431197, Clang c6195325c5, Swift add621a959)
Target: x86_64-apple-macosx10.9

**Comment by LoganWright** [comment]
@jjjjjeffrey right now, our current support is:

Vapor: 0.12.0
Xcode: 7.3
Swift 06-06

The master branch is updated to 06-20, but hasn't been released yet, expect to see support soon.

**Comment by jjjjjeffrey** [comment]
@LoganWright got it, thanks!

**Comment by tannernelson** [comment]
`0.13` using `06-20` has been released now.
