### ISSUE TITLE
Benchmark require

### ISSUE THREAD

**Issue by wildfiremedia** [qutheory/vapor#43]
Wish some day you can comparing PHP 7.x/HHVM 3.5 on Laravel 5.x and Lumen benchmark.

**Comment by mpclarkson** [comment]
I've benchmarked Vapor at 5000+ requests per second returning a json response using apache bench on my laptop. We're using PHP7 on one of our work dev servers and it is certainly much, much faster than 5. Not only is it faster but the memory usage is also significant lower. That being said, as PHP is interpreted, IMHO it's not going to be as fast as Swift, which is compiled.

**Comment by wildfiremedia** [comment]
Thanks for your benchmark and I assumed you posted in HN as well. What you think of Go can be a potential as a Laravel framework clone if there is?

**Comment by tannernelson** [comment]
I would love to have a benchmark of Vapor vs other web frameworks that we could put in the Wiki.

**Comment by elithrar** [comment]
Two option:

* Add Vapor to the Techempower benchmarks: https://www.techempower.com/benchmarks/#section=code&hw=peak&test=fortune
* Benchmark using a tool that is aware of [Coordinated Omission](https://groups.google.com/forum/m/#!msg/mechanical-sympathy/icNZJejUHfE/BfDekfBEs_sJ) (aka not `ab`). Doing your own benchmarks is still hard though: any non-trivial (writing static text isn't a benchmark) example takes a bit of work to write, and implementing that in other languages to compare can be a rabbit hole. Setting some goals (must turn a 8K data structure into JSON, must serialize and HMAC a cookie, etc) would be good. 

Plus hey, 5000/req/s is 18 *million* requests an hour. Even at their peak hour, most web services won't see that kind of traffic!

**Comment by wildfiremedia** [comment]
While I haven't try Vapor yet, if you could compile with -fast optimization
that will covert code to LLVM?

**Comment by tannernelson** [comment]
@elithrar The web frameworks benchmark looks like a great resource for development. I will add passing those benchmarks to the roadmap.

**Comment by tannernelson** [comment]
Added https://github.com/qutheory/vapor/wiki/Roadmap
