### ISSUE TITLE
Controllers not being displayed : Page not found error.

### ISSUE THREAD

**Issue by adriencanterot** [qutheory/vapor#444]
Hello, There's a bug that's been around for a while now.
It seems Vapor can't route resources with controllers anymore.
When I use the new syntax  as provided in the vapor-example : 
`let users = UserController(droplet: drop)
drop.resource("users", users)`

It's supposed to return for the following route : `http://localhost:8080/users`
the index page of the controller which contains the following JSON : 
`{ 'controller' : 'UsersController.index' }`
However it returns, and for every other actions on the controller : 
`{"error":true,"message":"Page not found"}`

I think the error has been around since Vapor 0.8.0 however it is still here with the new Droplet syntax.

I use macOS Sierra ß2 with Xcode 8.

**Comment by kdawgwilk** [comment]
I also am getting this on El Capitan and Xcode 8 Beta 2 running with the 6-20 snapshot

**Comment by tannernelson** [comment]
This has been fixed in the latest Vapor example.
