### ISSUE TITLE
Middleware not always called

### ISSUE THREAD

**Issue by snakecharmer** [qutheory/vapor#445]
Hi, i’m trying to extend my api using vapor. But i have some problems with the middleware routing.
The idea is to generate a new url /api/v2/ that extend the old /api/v1 and if the method isn’t overridden by swift the middleware should redirect to the old api:

I’ve tried to do something like this, but doesn’t work:

```
// My middleware, if the url starts with "group" then redirect the request to "redirectTo"
let v1Redirect = RedirectMiddleware(redirectTo: "http://v1.myapi.com", group: "/api/v2")

// Define the Apiv2 with a custom method all the other request not defined should fallback to v1 using v1Redirect
class ApiV2: RouteGroup {
    static func build(builder: RouteBuilder) {
        builder.get("test") { request in
            return "test"
        }
        
    }
}
//standard configuration
app.grouped("api") { api in
    api.grouped("v2") { group in
        group.add(ApiV2.self)
        group.add(middleware: [v1Redirect], method: .get, path: "*", handler: { request -> ResponseRepresentable in
            return "redirect"
        })
    }
}

```

or at least the redirect middleware is not always called (e.g):

/api/v2/test (works) 
/api/v2/tester (go inside the redirect middleware)
/api/v2/another/call (doesn’t work goes in "Page not found”)

**Comment by tannernelson** [comment]
This might be because `*` only matches what is between forward slashes. So `/api/v2/*/` will be matched, but `/api/v2/*/*` will not be matched.

**Comment by snakecharmer** [comment]
Then how can I configure a middleware to achieve a complete fallback route for a group?

**Comment by tannernelson** [comment]
We're going to be working on routing and grouping a bit in 0.15. I'll work on a solution to this during that.
