### ISSUE TITLE
NotFound to be part of the Vapor core?

### ISSUE THREAD

**Issue by proyb6** [qutheory/vapor#458]
I think the Not Found handling is implement on Middleware like Vapor University repo is an additional effort which could have been part of the core and the current code that rely on ```do {...}``` is excessive?

https://github.com/qutheory/vapor-university/blob/master/api/App/Middleware/NotFound.swift

**Comment by tannernelson** [comment]
Vapor core will have improved rendering of Abort.NotFound at some point, but it's my intention to allow users to catch the error in their own middleware to provide custom error pages.
