### ISSUE TITLE
What is the reliability of HTTP Server behind Vapor?

### ISSUE THREAD

**Issue by etemelkuran** [qutheory/vapor#482]
We all know that, it's excellent and elegant framework for Swift 3.
But what about the reliability of HTTP Server? Is it production close? Any performance results?

**Comment by tannernelson** [comment]
I've been using it to host my personal website for over 7 months and http://qutheory.io, http://vapor.university and many more are hosted with Vapor right now.

Benchmarks here:
https://medium.com/@qutheory/server-side-swift-vs-the-other-guys-2-speed-ca65b2f79505
