### ISSUE TITLE
The command `--port` seems  don't work

### ISSUE THREAD

**Issue by Shunzi007** [qutheory/vapor#483]
When I type `vapor run` or `vapor run serve --port=3000` in terminal, both say

```
Running VaporApp...
Server 'default' starting at 0.0.0.0:8080
```

The command `--port` seems  don't work

**Comment by tannernelson** [comment]
Port is no longer used as of Vapor 0.14. 

Edit the file `Config/servers.json` or use the flag `--config:servers.default.port=8080`

**Comment by Shunzi007** [comment]
Thanks!  Your artwork is awesome! Best wishes to vapor. It grows and makes swift  become a real website language!
