### ISSUE TITLE
Improper JSON serialization leads to user-controlled JSON contents

### ISSUE THREAD

**Issue by C0deH4cker** [qutheory/vapor#51]
The JSON serializer used does not properly validate key/value contents. One major issue is that `"` is not escaped, so users can create requests that craft extra keys in the serialized JSON. This can even be a security issue in certain web apps. I highly suggest using a JSON serialization library/framework for this task rather than writing a custom one. No reason to reinvent the (JSON) wheel :)

Example: http://qutheory.io/data/oops%22%7D,%22request.lol%22=%22hi?query=fail%22,extra=%22haxx

**Comment by tannernelson** [comment]
We are currently working on this in PR #46

**Comment by tannernelson** [comment]
Also referenced in issues #23 and #28.
