### ISSUE TITLE
Controller Refactor Proposal

### ISSUE THREAD

**Issue by ketzusaka** [qutheory/vapor#59]
Hello,

I wanted to make a proposal towards refactoring how Controllers work within Vapor. I've been working on a project that has some similarities to Vapor, and I wanted to see how my vision fit within it.

Under my system, I have calls into the router like so:
```swift
router.registerRouteWithPath("/channels/:channel", usingAction: ChannelDashboard.index)
```

`ChannelDashboard` conforms to `Controller`:

```swift
protocol Controller: class {
    var request: Request { get }
    init(request: Request) throws
}
```

It also implements the method `index`, which handles the actual request.

The key difference here and between what exists in Vapor today is that the request is passed into an initializer vs each request method. This would allow people to configure a variety of things at class initialization (which the router handles via currying, and I'll get into that soon). The way I'm using it is connecting to a DB, opening other sockets, and reading some extra data that all request methods would be interested in.

I feel like this would be useful because under the current `Controller` implementation you wouldn't be able to do what Rails calls a `before_filter` that would be able to look at request data; it'd have to wait until after the instantiation from the router closure.

In terms of implementation with currying, after the `Request` object is instantiated we can attempt try to instantiate the controller. This is what I'm doing under my system, which takes a generic type + the protocol, and records the instantiation call into a closure attached with a path:

```swift
func registerRouteWithPath<ControllerType: Controller>(path: String, usingAction action: (Controller) -> () throws -> ResponseType) {
        let actionCaller = { (request: Request) throws -> ResponseType in
            try action(try ControllerType(request: request))()
        }

        let route = Route(path: path, actionCaller: actionCaller)
        routes.append((path, route))
    }
```

This is possible because Swift creates a class method for each instance method that takes an instance of the class, i.e:

```swift
ChannelDashboard.index(ChannelDashboard) -> () -> ResponseType
```

That's a bit confusing, but it makes for a very simple registration API, and its something that's worked well in my use case where I don't need to worry about processing request information after the fact.

In addition, Vapor or its users could extend Controller to look at request and provide convenience methods to the contents of the Request object. I've done this with parameter values, and also added some methods for working with environment variables.

What are your thoughts on this? I'd be happy to implement them myself if there's interest.

Thanks!
~James

**Comment by tannernelson** [comment]
I think this could be solved by creating a function on the `Controller` class called `before(request: Request)` that would get called before the actual method is called.

But I think most of the before/after request functionality is already fulfilled by `Middleware`. Could you provide an example of something that wouldn't work with `Middleware`?

Additionally, currying is [being removed](https://github.com/apple/swift-evolution/blob/master/proposals/0013-remove-partial-application-super.md) in Swift 3.0

**Comment by ketzusaka** [comment]
Going from the bottom up:

Currying isn't being removed in Swift 3, just the odd syntax where you can do stuff like this:

```swift
func foo()() -> Void
```

That'll just need to be written as:

```swift
func foo() -> () -> Void
```

Putting something as a Middleware would work if we need it to apply to all controllers, but not if you want to define before/after functionality on a per-controller basis.

Adding a function that is called would also work. The only limitation I still see by doing that is stored properties on the controller that depend on the `Request` object wouldn't be able to be non-optional.

The particular use-case I have is that I made a protocol called `PollRetrievable`. This protocol has a requirement for a `Channel` property, and defines a method to read a poll: `readPoll() -> Poll?`. This method depends on data contained from the `Request` class (the channel), which is provided by a path parameter. By passing the data to the initializer, `Channel` can be a let and non-optional, but if this was setup in another method (such as `before(request: Request)`), the protocol would have to expect an optional and handle unwrapping inside of the `readPoll` method, and my controllers would need to define `Channel` as optional even though every operation within them require it to be defined. 

The `readPoll()` method is used by my `ChannelController` (which mentioned above is a `ChannelDashboard`) and my `PollController`. The `PollController` has mutation operations on a `Poll`, while the `ChannelController` just wants to display information about the `Poll`, but both need information about the currently open poll (for creating a new poll we verify that a poll isn't already open, so we expect the read method to return nil). In the initialization method defined by `Controller`, `readPoll()` is called in both `ChannelController` and `PollController`'s initializers, making a `Poll?` object available to all methods of the class. 

Lastly, I have an `AssetsController`, which doesn't care about the channel, has completely different routes, and doesn't depend on a `Poll`, so it doesn't conform to `PollRetrievable` and doesn't need a channel to operate on. This is why a Middleware for this wouldn't fit great.

Hopefully that all made sense. Thanks :)

**Comment by tannernelson** [comment]
That makes sense. 

Another issue I see with the current implementation of Controllers is that they might be the same between requests. I haven't tested this, but I think they are only initialized once. 

So if you stored any sensitive data for Person A's request on the controller, Person B might be able to see that.

**Comment by ketzusaka** [comment]
it looks like they are unique instances!

Is it worth me putting together a PR based on my proposals?

**Comment by tannernelson** [comment]
Yeah for sure.
