### ISSUE TITLE
Compile failure on OSX 10.10.5 , Xcode 7.1

### ISSUE THREAD

**Issue by tqtifnypmb** [qutheory/vapor#84]
/Library/Developer/Xcode/DerivedData/Vapor-hcyxlaippuixaudjkrczccpcvdiu/Build/Intermediates/Vapor.build/Debug/Vapor.build/Script-3AEEF4211C7F6D9F0099CBAE.sh: line 2: /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift: No such file or directory

**Comment by mpclarkson** [comment]
Which version of Xcode are you using?

**Comment by tannernelson** [comment]
I would recommend using [swiftenv](https://github.com/kylef/swiftenv) for ensuring you have the correct version of Swift installed for compilation. With swiftenv, just run `swiftenv install` in the root directory of a Swift project to install the appropriate Swift version.
