### ISSUE TITLE
DDoS risk

### ISSUE THREAD

**Issue by tqtifnypmb** [qutheory/vapor#85]
In function handleConnection(socket:) [File : SocketServer.swift]:
`while let request = try? parser.readHttpRequest(socket) {
            ...
        }`
Isn't it a chance for server to be attacked by DDOS? since parser.readHttpRequest() is blocked on socket reading.

**Comment by tannernelson** [comment]
DDoS / other attacks are outside of the scope of Vapor 1.0. The built-in `SocketServer` implementation can be replaced with any other Swift server that conforms to `Vapor.ServerDriver`.
