### ISSUE TITLE
Unable to build on OS X 10.11, Xcode 7.3 Beta

### ISSUE THREAD

**Issue by edgy360** [qutheory/vapor#87]
I performed a clean install of Swift and Xcode 7.3 beta and then configured a blank project using the [Getting Started](https://github.com/qutheory/vapor/wiki/Setup#getting-started) guide, however I get the below console output when building it.

```
$ swift build
Cloning https://github.com/qutheory/vapor.git
Resolved version: 0.2.6
Cloning https://github.com/czechboy0/Jay.git
Resolved version: 0.3.5
Compiling Swift Module 'Jay' (19 sources)
Linking libJay.dylib
Compiling Swift Module 'JayExample' (1 sources)
Compiling Swift Module 'Vapor' (36 sources)
Linking JayExample
Linking libVapor.dylib
Compiling Swift Module 'Vaportest' (6 sources)
Compiling Swift Module 'VaporDev' (2 sources)
Compiling Swift Module 'TestProject' (1 sources)
Linking VaporDev
Linking TestProject
ld: framework not found XCTest for architecture x86_64
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a.xctoolchain/usr/bin/swift-build-tool -f /Users/jamie/Development/TestProject/.build/debug.yaml default
```

Swift version:
```
$ swift --version
Apple Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift fc261045a5)
Target: x86_64-apple-macosx10.9
```

**Comment by LoganWright** [comment]
@edgy360 There's work on the way to avoid this error, but if you're hitting it, try the following command `rm -rf /Packages/Vapor-{version}/Tests`:

Likely:

```
rm -rf /Packages/Vapor-0.2.6/Tests
```

You'll have to do this each time you upgrade or refetch your packages until the issue can be addressed.

**Comment by edgy360** [comment]
Thanks @LoganWright, that fixed the issue. :)

**Comment by tannernelson** [comment]
The `./run` command in [Vapor Example](https://github.com/qutheory/vapor-example) can be used in the interim. We are working with the SPM team to get this fixed.
